potatolondon/djangae

djangae/db/backends/appengine/base.py, djangae/tests.py
Think this is enough to force values to unicode when persisting. I ran into this bug when assigning the result of django.template.defaultfilters.slugify(..) to the field.
In theory the test should be OK. Not sure how one is supposed to run djangae's tests.
=> 148 non unicode strings

djangae/db/unique_utils.py, djangae/tests.py
This adds support for using unique markers with ListField and SetField (e.g. a value can appear in the field for only one instance)
=> Add unique constraint support for ListField and SetField

djangae/indexing.py, djangae/tests.py
I created a special index (icontains) for model field which had objects with empty values. This caused this bug:
```
BadValueError: May not use the empty list as a property value; property _idx_icontains_location is [].
```
This patch is making sure we always return None instead of empty list for all special indexes.
=> Fix for error of creating special indexes for fields with empty values

djangae/test.py, djangae/tests.py
This PR adds a context manager for testing code against an inconsistent database.
=> Add an inconsistent_db context manager for testing

djangae/fields/iterable.py
Pedantry.  But if we don't comment it then someone will "fix" (i.e. break) it again in the future.
=> Adding a comment about why we allow a SetField's value to be set using a list

djangae/db/backends/appengine/dnf.py, djangae/tests.py
Hi.
I fixed exclude() bug when used with __in on an empty list.
This patch fixes a failed test in "test_in (lookup.tests.LookupTests)".
<pre>
======================================================================
FAIL: test_in (lookup.tests.LookupTests)
----------------------------------------------------------------------
File &quot;django_tests/lookup/tests.py&quot;, line 463, in test_in
'&lt;Article: Article 1&gt;',
File &quot;djangae-testapp/lib/django/test/testcases.py&quot;, line 829, in assertQuerysetEqual
return self.assertEqual(list(items), values)
AssertionError: Lists differ: [] != [u'&lt;Article: Article 5&gt;', u'&lt;A...
Second list contains 7 additional elements.
First extra element 0:
&lt;Article: Article 5&gt;
- []
+ [u'&lt;Article: …
=> Fix exclude() bug when used with __in on an empty list

djangae/db/backends/appengine/commands.py, djangae/indexing.py, djangae/tests.py
Hi.
I added some code to deal with 'id_iexact' query.
This patch fixes a failed test in "test_lookup_int_as_str (lookup.tests.LookupTests)".
<pre>
======================================================================
FAIL: test_lookup_int_as_str (lookup.tests.LookupTests)
----------------------------------------------------------------------
File &quot;django_tests/lookup/tests.py&quot;, line 57, in test_lookup_int_as_str
['&lt;Article: Article 1&gt;'])
File &quot;djangae-testapp/lib/django/test/testcases.py&quot;, line 829, in assertQuerysetEqual
return self.assertEqual(list(items), values)
AssertionError: Lists differ: [] != [u'&lt;Article: Article 1&gt;']
Second list contains 1 additional elements.
First extra element 0:
&lt;Article: Article 1&gt;
- …
=> Fix 'id_iexact=' query

djangae/contrib/mappers/urls.py
mapreduce is an external library because the one bundled in the sdk is advised against, this just wraps a try around the import
=> import fix to make sure mapreduce is not a dep

djangae/db/backends/appengine/commands.py, djangae/tests.py
Without this patch, djangae could not execute the query "TestUser.objects.filter(id__in=[self.u2.id, self.u3.id, self.u4.id]).order_by('id')".
<pre>
File &quot;djangae-testapp/lib/djangae/tests.py&quot;, line 1123, in test_ordering
self.assertEqual([&quot;B&quot;, &quot;C&quot;, &quot;D&quot;], [x.username for x in users])
File &quot;djangae-testapp/lib/django/db/models/query.py&quot;, line 96, in __iter__
self._fetch_all()
File &quot;djangae-testapp/lib/django/db/models/query.py&quot;, line 857, in _fetch_all
self._result_cache = list(self.iterator())
File &quot;djangae-testapp/lib/django/db/models/query.py&quot;, line 220, in iterator
for row in compiler.results_iter():
File &quot;djangae-testapp/lib/django/db/models/sql/compiler.py&quot;, line 713, in …
=> Fix KeyError: '__key__' in django_ordering_comparison

djangae/contrib/mappers/pipes.py, djangae/tests.py
I have run the coverage and noticed that there were no tests available for normalise_field_value and decimal_to_string. Therefore, I have added additional tests for them.
<pre>
1. Before
Name                   Stmts   Miss  Cover
------------------------------------------
lib/djangae/db/utils     173     25    86%
2. After
Name                   Stmts   Miss  Cover
------------------------------------------
lib/djangae/db/utils     173     10    94%
</pre>
Thanks.
=> Add tests for djangae.db.utils.normalise_field_value and djangae.db.utils.decimal_to_string

djangae/db/backends/appengine/commands.py
This patch speed up 'get_field_from_column' by caching fields and executing loop only once for each model.
Thanks.
=> Speed up 'get_field_from_column' by caching fields

djangae/contrib/pagination/decorators.py
I tried to create a paginated_model like that:
```
@paginated_model(orderings=[('-field',)]) 
```
and encountered this error: `TypeError: 'tuple' object does not support item assignment`
=> Fixed error with trying to assign tuple elements in pagination.

djangae/test.py
Fixes #239 
(the saved taskqueue stub saved in _fixture_setup would be later overrided by a fresh stub set up by NosePlugin.startTest())
=> Change from fixture_setup to setup.

djangae/contrib/pagination/paginator.py, djangae/contrib/pagination/tests.py
Sooo... if you paginated your objects in a way that the last page has less objects than your `per_page` variable, then it threw an `out of range` error. I added some tests and fixed it. :gift:
=> Added additional pagination tests, fixed paginator bug

djangae/sandbox.py
when the subprocess module is loaded it imports os, os needs to be imported first otherwise a hairy situation can occur
=> Fix allow_modules reload order

djangae/contrib/pagination/paginator.py
Not 100% sure about the contrib.paginator code, but this looks like a bug to me, as `results` is previously sliced.
=> Fixed number of results per page

djangae/indexing.py, djangae/tests/tests.py
Django supports this on SQL automatically as SQL allows string comparisons with dates and datetimes. This now works by indexing the isoformat of the date or datetime.
=> Support contains lookups on values that have an isoformat method

djangae/contrib/gauth/management/__init__.py, djangae/contrib/gauth/models.py, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/dbapi.py, djangae/db/backends/appengine/dnf.py, djangae/db/utils.py, djangae/fields/computed.py, djangae/fields/iterable.py, djangae/patches/contenttypes.py, djangae/test_runner.py, djangae/tests/tests.py
This PR includes the changes necessary to support both Django 1.6 and 1.7. There are still a few tests failing but:
- In Django 1.6, there are now only 2 errors, 0 failures
- In Django 1.7, there are now 5 errors, 2 failures
Both of which are fewer than what's in master currently. When this branch is merged, the testapp will be upgraded to 1.7 and Travis will run tests on that until we can sort out side-by-side testing.
I should also add, the following new functionality is now available:
- Orderings can be specified with extra() ... although obviously don't do that
- Extra selects now support basic arithmetic and aliases
- Permission creation is now properly disabled conditionally
- We are now able to skip selected Django tests by adding them to test_runner.py
- The test runner can be …
=> Django 1.7 support

djangae/management/commands/runserver.py, djangae/sandbox.py
Adding the `--external-port` flag depending on the SDK version. Newer versions need it to be passed in. #307
=> Fixing runserver command for the new App Engine SDK 1.9.19

djangae/db/constraints.py, djangae/tests/tests.py
We also don't support multiple list/set fields in a unique_together. We should warn against that in other places too probably.
=> Fix a bug where a unique check on a long list would throw an error

djangae/db/utils.py, djangae/tests/tests.py
Django doesn't call get_default() on an update, this is problematic on a schemaless database because we have no UPDATE query that could pre-populate it for us, so we always call get_default if the field is not-nullable, has a value of None, and has a default
=> Make sure we set the default even on an update (Django doesn't do this)

djangae/db/backends/appengine/base.py
Django 1.7 is very eager to validate all integer fields based on reported limits - including ForeignKeys. Reporting all integers limited at 64bit max makes using FK's much easier.
=> Making all database integer limits equal to a 64bit maxint.

testapp/install_deps.py
Our `install_deps` script that install dependencies for tests was installing always 1.6.0 and 1.7.0, not the latest release of 1.6.x and 1.7.x. Fixed now ;)
=> Installing the latest django version from a release

djangae/contrib/gauth/common/models.py
This was causing breakage with Django 1.7.
=> Import `urlquote` from its source module, not from another module which happens to import it.

djangae/fields/related.py, djangae/tests/test_connector.py, testapp/testapp/settings.py
Turns out that we need to return the actual instances, because we can't do what FK and M2M do as they are special cased in the Python Deserializer :(
=> Fix relatedsetfield deserialize

djangae/db/transaction.py, djangae/tests/test_connector.py
e.g.:
```python
class Cls(object):
@transaction.atomic
def txn(self, arg):
...
```
Which fails with `TypeError: txn() takes exactly 2 arguments (1 given)`, because in `ContextDecorator.__call__()`, `self` arg is always going to be the decorator itself, not the instance of the class the method was called on (and we swallow it anyway).
Extended a couple of tests to demonstrate this.
The only solution I could think of is with some descriptor magic. If the decorator is a descriptor, when it’s used on an instance method, `ContextDecorator.__get__()` will be used to access it, which is passed the instance it’s called on… so we can insert that instance into the args we call the func with (which becomes `self` inside the function).
Alternatively, an easy workaround is to just use `atomic` as a …
=> Made `@atomic` decorator work on instance methods.

djangae/db/transaction.py, djangae/tests/test_connector.py
`transaction_started` was only set `False` in `__init__()`, which is fine for single-use context managers, but when decorating functions/methods it can leave the decorated method in a state where it thinks it’s still in a transaction after it finishes.
In certain nesting patterns `__exit__()` gets confused, and ultimately pops a few too many times and drops its load on the floor.
=> Fixed a stack underflow with nested transactions using the `@atomic` decorator

djangae/contrib/pagination/decorators.py, djangae/contrib/pagination/tests.py
Fixed a bug that was adding a field twice to the paginated class. Tests
=> Supporting datetime fields in contrib.pagination

djangae/blobstore_service.py, djangae/management/commands/runserver.py, djangae/sandbox.py, djangae/tests/test_storage.py, testapp/testapp/settings.py
This PR adds a local wsgi handler which emulates the blobstore service when running the local sandbox. This allows the BlobstoreStorage backend to function when running management commands, tests etc.
=> Local blobstore service

djangae/storage.py, djangae/test_runner.py, testapp/testapp/settings.py
There were two failing tests in `model_forms.tests.FileAndImageFieldTests`. This makes them pass + removes duplicated tests from the test suite (one of them was failing because tests were duplicated in the test suite).
=> Resolved two failing tests in Djangae for Django 1.7

djangae/storage.py, djangae/tests/test_storage.py
When uploading PDFs for instance, the Storage backend uses PIL's `get_serving_url` which raises a `TransformationError` exception as the file can't be transformed to image. This makes it a bit more fool-proof.
=> Handles TransformationError exception when getting blob's URL

djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py, djangae/tests/test_connector.py
Test case attached.
Should throw `DoesNotExist` but results in the following stack trace:
```
File "...djangae/djangae/tests/test_connector.py", line 1137, in test_unusual_queries
TestFruit.objects.get(name='')
File "...djangae/testapp/libs/django/db/models/manager.py", line 151, in get
return self.get_queryset().get(*args, **kwargs)
File "...djangae/testapp/libs/django/db/models/query.py", line 304, in get
num = len(clone)
File "...djangae/testapp/libs/django/db/models/query.py", line 77, in __len__
self._fetch_all()
File "...djangae/testapp/libs/django/db/models/query.py", line 857, in _fetch_all
self._result_cache = list(self.iterator())
File "...djangae/testapp/libs/django/db/models/query.py", line 220, in iterator
for row in compiler.results_iter(): …
```
=> Get-by-key when key is an empty string fails

djangae/contrib/pagination/decorators.py, djangae/contrib/pagination/tests.py, docs/pagination.md
* Allows `@paginated_model` to accept a single field name as an ordering, as well as a tuple/list of field names.
* Improved documentation.
This will close #303.
=> Improve paginator

djangae/db/utils.py, djangae/tests/test_connector.py
Test to reproduce attached.
Will collaborate with @asendecka to add a fix to this PR.
=> `django_ordering_comparison` can’t handle datetimes with null values

djangae/management/commands/runserver.py
So, the idea here is to "cheat" Django's command's attributes adding the options from the sandbox as new elements in `option_list`.
I'm doing it in the `__new__` method so `option_list` can still be extended if someone wanted to extend the runserver command and add more options to it.
I wanted to add something to the docs, but I'm not sure in what section it would fit?
=> runserver supports the same commands than dev_appserver.py

djangae/contrib/gauth/datastore/management/__init__.py, djangae/contrib/gauth/datastore/permissions.py, djangae/contrib/mappers/readers.py, djangae/contrib/uniquetool/models.py, djangae/db/utils.py, djangae/patches/contenttypes.py, djangae/test_runner.py, djangae/views.py
This is branched off query-construction-refactor, to make sure that this PR won't create more failing tests. I tested it locally, and it returns the same numer of broken tests ;)
=> Getting rid of RemovedInDjango19Warning deprecation warnings

djangae/db/backends/appengine/commands.py
This fixes the bug where `Model.objects.filter(**kwargs)` and `Model.objects.exclude(**kwargs)` are not always disjoint sets.
=> fix for `!=` queries: groupby requires a sorted list

djangae/contrib/gauth/common/backends.py, djangae/contrib/gauth/tests.py, docs/gauth.md
DJANGAE_FORCE_USER_PRE_CREATION introduced
* if we want to prevent creation of Users every time someone logged with their Google Account hits our app, we can use DJANGAE_FORCE_USER_PRE_CREATION settings. Thanks to that we enforce that only pre-created users are allowed to log in.
* there is one exception: superusers always will have User object created.
* tests & documentation added.
=> Force user precreation

djangae/apps.py, djangae/db/backends/appengine/caching.py, djangae/tests/test_transactional.py
It seems that sometimes request_started/finished signals weren't connected properly resulting in strange behaviour across requests.
=> Additional transaction tests

djangae/patches/contenttypes.py
Default `allow_migrate` is now defined as:
```
def allow_migrate(self, db, app_label, **hints):
```
We should be using `allow_migrate_model` instead. 
Django docs: https://docs.djangoproject.com/en/1.8/topics/db/multi-db/#allow_migrate
=> Signature for allow_migrate is different now. 

djangae/tests/test_connector.py
Tests showing that `exclude` does not play nicely with `__in`.
=> Exclude count not working

djangae/storage.py
When using create_upload_url with a bucket name argument the files are uploaded to GCS, and an encoded blob key is passed to the app. Instead of a hash only the key has a form of: `encoded_gs_key:XXXXX` (where XXXX is the b64 encoded gcs filename). 
Pulling this simple change to our regex we can make our FileUploadHandler support gcs uploads through blobstore.
=> Fix our handler to support files uploaded to GCS via blobstore.

djangae/db/backends/appengine/caching.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/context.py, djangae/tests/test_caching.py
Try use cache with multiple entities at once when possible.
That gives a lot of speed up since it reduces number of calls to cache.
=> Caching refactor - speedup

docs/gauth.md
Wrong path for `AUTHENTICATION_BACKENDS`.
Thanks Samuel Mathieson.
=> Fix mistake in gauth documentation.

djangae/db/backends/appengine/query.py
This pull request expands the exception message when encountering multiple inequality filters to include the column names.
=> Improve exception message when encountering multiple inequality filters

djangae/management/commands/runserver.py
validate(..) was deprecated in Django 1.7, and has been removed in 1.9.
This change is incompatible with Django 1.6.
=> Updated runserver command to use check(..) instead of validate(..).

djangae/contrib/gauth/common/models.py
For pre-creation.
You still have to fill in a password when pre-creating, I don't know how to fix that.
=> Allow User ID to be blank

djangae/tests/test_connector.py
I wasn't sure whether doing `.filter(field__gt=a, field__lt=b)` was allowed or not.  It seems that it is (the Datastore stub doesn't complain), so adding that to the checks that this test does.
=> Adding an extra check to the `test_notsupportederror_thrown_on_too_many_inequalities` test

djangae/test_runner.py
=> Making the `SkipUnsupportedRunner` only ignore `NotSupportedError`s in Django's tests, not in Djangae's

djangae/db/backends/appengine/query.py, djangae/tests/test_connector.py, testapp/djangaeidx.yaml
So this pull request is fixing the __year lookup, that was throwing UnSupportedError for a while, and that bug was hidden by our setup to automatically skip Django tests that throw UnSupportedError.
We incorrectly validated query value [here](https://github.com/potatolondon/djangae/commit/632113d03ccd34c05116723fe4f141677f37c725#diff-5f1fd58426c71048b283812e6198689eR122). The value in this case was an integer (year), and `validate_can_be_indexed` method checks for datetime (that's a correct check, but for **indexing**, not lookup). 
I also added a test for `__year`, and fixed another failing test that was hidden because of that bug.
=> Fix __year index lookup

djangae/storage.py
Otherwise, when doing `field.url` we get things like `https%3A//storage.googleapis.com/<file>` and we can't use it as `href` in a link.
=> Only quote the bucket and filename for a Cloud Storage URL

djangae/contrib/mappers/pipes.py, djangae/contrib/mappers/readers.py, djangae/contrib/uniquetool/models.py, djangae/contrib/uniquetool/tests.py, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/caching.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/compiler.py, djangae/db/backends/appengine/context.py, djangae/db/backends/appengine/query.py, djangae/db/constraints.py, djangae/db/unique_utils.py, djangae/db/utils.py, djangae/tests/test_caching.py, djangae/tests/test_connector.py, djangae/tests/test_query_transform.py, docs/db_backend.md, testapp/testapp/settings.py
This PR adds multiple datastore connections using namespaces. Note that like Django databases, cross-namespace foreign keys are not support.
This introduces a slight backwards incompatibility in the cache key naming (all cache keys now start with a namespace and a ":", if there is no namespace the cache key starts with a ":") so if you deploy to an existing version you will need to flush the cache.
=> Namespace support

djangae/db/backends/appengine/commands.py, djangae/tests/test_connector.py
Djangae should raise an error if it's given a stupid value for a field when creating (as Django does).
Fixes #493
=> Validate fields when inserting

djangae/db/backends/appengine/compiler.py, djangae/db/backends/appengine/query.py, djangae/tests/test_connector.py
These changes allow us to order by special appengine properties (E.g __scatter__ or __key__) although it's mainly for __scatter__
=> Make it possible to order by __scatter__

djangae/fields/counting.py
Ideally these saves would be a `instance.__class__.objects.filter(pk=instance.pk).update(new_shards)`, but because you can't append to a `set()` like that we use `models.Model.save` instead to avoid custom `save` methods.
=> Make sharded counter object saving safer 

djangae/db/backends/appengine/caching.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/context.py, djangae/db/caching.py, djangae/db/transaction.py, djangae/db/utils.py, djangae/models.py
This backports the latest caching, transaction and context code from HEAD to the 1-6-support branch. This is necessary because the previous caching code is broken, buggy and causes huge performance issues. We don't really support 1.6 any more (AT ALL!) but there are people using this code in the wild still and the backport was fairly trivial so I did it anyway.
This PR also includes the latest QueryByKeys implementation - it seemed silly not to improve this at the same time!
If you are using Djangae on Django 1.6. **Don't.**
=> 1 6 memcache backport

djangae/storage.py, djangae/tests/test_storage.py, testapp/install_deps.py
Hi,
This change makes the Google Cloud Storage storage backend default to _not_ setting an ACL by default, which means GCS will apply the default ACL (which happens to be project-private if the bucket permissions have not been edited).
It is still possible to set an explicit ACL with the google_acl keyword argument.
https://cloud.google.com/storage/docs/access-control?hl=en#predefined-project-private
=> Cloud storage permissions

djangae/contrib/mappers/pipes.py, djangae/contrib/mappers/readers.py, djangae/contrib/uniquetool/models.py
This fixes an bad API change which added "db" as a kwarg to all mapper functions - this was introduced with the namespace support merge. Apologies if this broke your mappers!
=> Remove extra "db" parameter from mappers

djangae/db/backends/appengine/commands.py, djangae/db/utils.py, djangae/tests/test_connector.py
This fixes a bug where no results would be returned when combining a filter, with a pk__in with more than one entry, and a projection without including the filtered column. Edge cases :disappointed:
=> Fix a bug when filtering on projection queries. Small performance tweaks

djangae/fields/related.py, djangae/tests/test_db_fields.py
Turns out that querying on `filter(some_related_list_field=some_instance)` was dying, when actually this is the valid way to query (because fields are indexed with multiple values this is the right way is equality until we implement a more intuitive __contains lookup). I'm guessing until now people have been querying on `_ids` or something.
=> Fix relatedfield exact lookups

djangae/fields/related.py
Fixes running migrate for models with RelatedSetFields, without the fix hardcoded keyword-arguments are duplicated.
=> Remove any hardcoded arguments in RelatedIteratorField.deconstruct

djangae/db/backends/appengine/query.py, djangae/tests/test_connector.py
Text properties aren't indexed on the datastore, and ordering by one will return an empty queryset.
The error suggests a workaround by using a ComputedCharField and storing the first 500 chars which in most
cases will give you the right ordering (obviously it won't if the strings differ at character 501+)
=> Don't allow ordering by a TextField

djangae/__init__.py
Avoids potential conflict if you add a global package called `patches`, and will avoid breakage if this moves to Python 3.
=> Make import of `patches` explicitly relative.

djangae/contrib/gauth/backends.py, djangae/contrib/gauth/common/backends.py, djangae/contrib/gauth/settings.py, djangae/contrib/gauth/tests.py, docs/gauth.md
Hi,
This fixes #592 by changing the base App Engine auth backend to return None if it is not passed a valid App Engine user. Previously it would raise  TypeError.
Also, quite importantly, this change removes the legacy djangae.contrib.gauth.backends module.
**This is a breaking change for projects which still specify the old backend name in their `AUTHENTICATION_BACKENDS` settings.** Those projects can update their settings to specify `djangae.contrib.gauth.datastore.AppEngineUserAPIBackend `.
Hope this helps,
Dave
=> Auth backend type error

djangae/contrib/consistency/tests.py, djangae/contrib/gauth/tests.py, djangae/contrib/uniquetool/tests.py
Hi,
This tidies up a few test cases which weren't calling super() in their setUp or tearDown methods.
Fixes #598.
Dave
=> Make sure to call super() in TestCase setUp and tearDown methods.

djangae/sandbox.py
directories.
* for some reason calling gettempdir might end up with thread.error
(somehow we the lock is released too fast). We don't really know why
this is the case, but we suspect changing tempfile module in
`allow_modules` might contribute to that.
* we decided to remove gettempdir completely and provide the list of
default tmp directories directly in `allow_mode_write`.
=> Don't use gettempdir to get the list of possible default tmp

djangae/settings_base.py
This is an addition to @chargrizzle awesome changes. 
We've been using this on 2 projects for more than a month and it seems to work perfectly. 
This is primarily useful for front-end developers. 
I wasn't sure if it should go into `settings_base.py` or [`management/commants/runserver.py`](https://github.com/potatolondon/djangae/blob/master/djangae%2Fmanagement%2Fcommands%2Frunserver.py#L16). `settings_base` seems to make more sense as you can see all default settings in one place.
Some stats (MacBook Air 2015, 2.2Ghz i7, SSD)
When changing a SCSS file (compiled by `node-sass` via `webassets`):
* without this fix - **8 seconds** to reload the page
* with this fix - **1 second** to reload the page
When changing a JS file (compiled by `closure-library` via `webassets`):
* without this fix - …
=> Restart GAE only when a .py or .yaml file changes

djangae/core/validators.py, djangae/fields/__init__.py, djangae/tests/test_db_fields.py
- add MaxBytesValidator class
- add custom djangae CharField with max_lenght set to 1500 bytes (current GAE
limit) by default and MaxBytesValidator added to its validators
- add tests for the new field
=> Improvements to CharField (issue #333)

djangae/test.py
With CloudSQL projects, sometimes you need to use Django's TransactionTestCase, but it's handy if that class would have the helpers for dealing with TaskQueues.
=> Adds a TransactionTestCase in djangae like the one in Django

djangae/test.py
This seemed to break some existing tests as the task queues stopped working on tests.
=> Reverts the usage of _pre_setup instead of setUp

CHANGELOG.md, djangae/fields/json.py, djangae/tests/test_db_fields.py
After commit ad9de1c4ab7495c4dfa5fb2b3f110cb28446c256 and removing any references to deprecated `SubfieldBase` in `JSONField` we ended up with the problem of incorrect default value. We cannot provide it as a string anymore, so we removed dumping the value and made sure that we provide `{}` if the default value is not provided. 
We also implement `to_python` method, since Django documentation states it is necessary for more complicated custom fields anyway.
=> JSONField fix after removing SubfieldBase

djangae/fields/json.py, djangae/tests/test_db_fields.py
Fixed weird regression issue with JSONField that meant that defaults were being returned as strings '{}' instead of python data structs as they were before the move away from the Subfield meta class inheritance. Not entirely sure if this is the correct fix, but thought I would give it a whirl and at least give the issue better visibility with some sample code and tests. With this fix in place and my test, all tests are passing minus the one that was failing before I made any changes. :)
=> Fixed weird regression issue with JSONField.

docs/consistency.md
Currently the docs for the eventual consistency app show an example config that uses camel-case model names. Unfortunately, that seems to fail silently. Converting the model name to lower case does the trick though. 
Updating the docs to make sure it's a bit clearer.
=> Correcting config in eventual consistency docs 

djangae/db/consistency.py
There used to be a `.get()` in here, but now it's a `.filter()` so the try/except is unnecessary.
=> Removing unnecessary try/except from db.consistency

djangae/contrib/gauth/common/backends.py, djangae/contrib/gauth/middleware.py, djangae/contrib/gauth/settings.py, djangae/contrib/gauth/tests.py, docs/gauth.md
Hello,
These changes replace the 2 settings for the Google Accounts authentication backend with a new setting `DJANGAE_CREATE_UNKNOWN_USER`, as described in #595 .
One difference is that the new logic will not raise `IntegrityError` when `DJANGAE_CREATE_UNKNOWN_USER=False` and there is an existing user with a matching email address.
The setting is named to be consistent with Django's RemoteUser backend, which has a `create_unknown_user` attribute that controls a similar feature to do with auto-creating user accounts.
David B.
=> Simplify auth backend

djangae/db/backends/appengine/caching.py, djangae/db/backends/appengine/commands.py, djangae/db/constraints.py, djangae/tests/test_caching.py, djangae/tests/test_connector.py, docs/db_backend.md
This PR does the following:
- Improves performance of inserts by performing fewer RPC calls
- Improves the performance of constraints by updating markers in xg transactions, which could potentially also fix race conditions
- Limits bulk inserts to the max-entity-groups per transaction value if there are unique constraints or pre-defined primary keys. This is necessary for reliable behaviour on failure (to prevent some entities being committed and others not). If you need to bulk_create more then either don't specify keys, disable unique constraints, or bulk create in a loop and handle any errors appropriately.
- Doesn't cache in memcache on insert, only in the context cache - this is to prevent potential inconsistencies between what's in the datastore vs what's in memcache
- Fixes a bug …
=> Improve unique constraints

djangae/fields/json.py, djangae/tests/test_db_fields.py
This protects against the easy "default={}" mistake which causes multiple instances to reference the same dictionary.
=> Disallow dict list default

docs/installation.md
it's now default and used whether 2fa is enabled or not
=> the --oauth2 option is no longer needed

djangae/fields/related.py, djangae/tests/test_db_fields.py
Fails when related iterated fields model is set as string
=> RelatedIterator fix

djangae/management/commands/runserver.py, djangae/settings_base.py
In the same way that we patch the SDK's file watcher so that we can ignore files that match a particular regex, this extends that to allow us to ignore whole directories that match a particular regex.
Note that in both cases we only get the file or directory **name**, not the whole path, which is annoying.  But hooking in where we can look at the whole file path would require monkey patch much more code.
The main aim here is to ignore the 'google_appengine' directory (which itself contains at least 3 different versions of the django source code), and thus we can avoid the "There are too many files in your application" and in doing so avoid some of our own source code not being monitored.
Of course an alternative solution is to not put the SDK in the 'sitepackages' folder.  :fire: …
=> Extending runserver's file watcher patching to allow ignoring of directories

djangae/contrib/mappers/readers.py, djangae/contrib/security/middleware.py, djangae/contrib/uniquetool/models.py, djangae/db/backends/appengine/indexing.py, djangae/test.py
Hi,
This change just tidies up some logging calls that were using string formatting for arguments, instead of letting the logging module handle the formatting itself.
And for the security middleware, display non-https urls with %r formatting because that makes it easier to see exactly what the value was when there is whitespace at the beginning of the string.
David B.
=> Use positional arguments to logging calls instead of formatting.

docs/security.md
Hi,
This change adds a note about the `dumpurls` command to the security section of the docs, fixing #654 .
Dave
=> Added a note about the `dumpurls` management command in the docs.

CHANGELOG.md, djangae/fields/json.py, djangae/forms/fields.py, djangae/tests/test_form_fields.py
Previously, if we had a JSONField on a model, and we edited that in a form, then we would take the raw string from the POST and essentially pass it straight through to the field in the DB.  If you then reloaded the object from the DB then it would parse the JSON back into python, but there were 2 problems:
1. We didn't do any validation on the JSON string before saving it (i.e. didn't attempt to parse it).
1. If you overrode your form's `clean` method and accessed `self.cleaned_data['my_json_field']` then you would have a string, not the proper object (which is contrary to how things like BooleanFields work, where `cleaned_data` gives `True` or `False`, not `"1"` or `""`.
This pull request fixes that.
=> Fix JSONField behaviour in forms

CHANGELOG.md, djangae/forms/fields.py, djangae/tests/test_form_fields.py
This was causing an error whereby if you submitted a form with an empty value for a ListField then it would die with `"You cannot set a ListField to None, did you mean []?"`.
Note that this PR is branched from #652 and should not be merged until that is merged.
=> Fixing ListFormField.clean to return [] instead of None for empty values

djangae/fields/counting.py, djangae/fields/related.py
This renames the first positional argument of related fields from "model" to "to" which is more consistent with Django's ForeignKey etc.
=> Clean up of the deconstruct methods on Related fields

djangae/sandbox.py
- Previously if two libraries were in both sitepackages and appengine/libs, the later would be resolved.
- Now any locally managed third party libraries take precedent.
This is a workaround for the bigger problem of all appengine/lib paths being added to sys.path. Only the libraries specified in app.yaml should be available for use (this currently leads to a difference in local and production behaviour).
=> Make sure libraries in sitepackages directory have precedent over bundled appengine libs

CHANGELOG.md, djangae/test.py
When writing tests for an app it would be useful to have some built in assertion methods to verify that handlers defined in app.yaml have the correct login configuration.
This would reduce the likelihood of that line being removed and the change not being noticed (it could have profound security implications after all).
It would also make it more explicit that requests processed by a handler require users to login in the tests. Currently this can be quite transparent.
Obviously these assertions don't need to test that the configuration is correctly processed by appengine (those tests already exist in the SDK), but only assert that presence of the correct configuration for a defined handler.
=> Add custom test assertions to check if login:admin or login:required protect a handler

djangae/contrib/gauth/datastore/admin.py
Hide password field and make username optional.
See #522. This partially fixes #97.
=> User pre-creation from Django admin

djangae/db/transaction.py, djangae/tests/test_transactional.py
Reverts potatolondon/djangae#668
That PR seems to cause this problem:
```
Internal Server Error: /_admin/login/
File "sitepackages/django/core/handlers/base.py", line 223, in get_response
response = middleware_method(request, response)
File "sitepackages/django/contrib/sessions/middleware.py", line 50, in process_response
request.session.save()
File "sitepackages/django/contrib/sessions/backends/db.py", line 56, in save
return self.create()
File "sitepackages/django/contrib/sessions/backends/db.py", line 41, in create
self.save(must_create=True)
File "django/contrib/sessions/backends/db.py", line 65, in save
obj.save(force_insert=must_create, using=using)
File "django/db/models/base.py", line 734, in save
force_update=force_update, …
```
=> Revert "Use a stack for state in the atomic + non_atomic decorators. Fixes #667"

CHANGELOG.md, djangae/db/backends/appengine/indexing.py, djangae/tests/test_connector.py
Fixes issue described on mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/djangae-users/erIUL3LZ9GA/ZWo0OAl1AQAJ
`__iexact` queries now work correctly when the indexed value contains an underscore.
=> Fix iexact index with underscores

.travis.yml, djangae/db/backends/appengine/query.py, djangae/fields/counting.py, djangae/fields/related.py, djangae/patches/contenttypes.py, testapp/install_deps.py, testapp/testapp/settings.py
So these are a couple of fixes that we can merge now to master even though tests don't pass on Django 1.10 alpha 1 and master branches yet. They're marked as allowed to fail in Travis setup though. 
Fixed in this PR:
- Adds 1.10a1 and master to Travis config. Allows them to run and fail. Changes to install_deps and settings to allow for version number 1.10a1
- We were calling `super` on RelatedSetField in RelatedListField
- Model reference in ShardedCounterField needs to be a string, otherwise Django migrations fail on creating testing db
- Added more flexibility so 1.10 or 1.11 doesn't fail because they're not in query factories.
=> Fixes to make Djangae run on Django 1.10 alpha 

CHANGELOG.md, djangae/apps.py, djangae/contrib/contenttypes/__init__.py, djangae/contrib/contenttypes/apps.py, djangae/contrib/contenttypes/management.py, djangae/contrib/contenttypes/models.py, testapp/testapp/settings.py
Fixes #682 
- Moves ContentType patch to djangae.contrib.contenttypes
- If django.contrib.contenttypes is in INSTALLED_APPS, but not djangae.contrib.contenttypes, raises an ImproperlyConfigured error
=> Fixes #682 - Move ContentType patch to djangae.contrib.contenttypes

CHANGELOG.md, djangae/db/transaction.py, djangae/tests/test_transactional.py
Fixes #667 and the breakage caused by the first attempt to fix that, which was #668.
- `transaction.atomic` and `transaction.non_atomic` decorators can now be used recursively (and in multiple threads) without causing exceptions, explosions or earthquakes.
=> Fix transaction decorators

CHANGELOG.md, djangae/contrib/gauth/common/backends.py, djangae/contrib/gauth/tests.py
- Added a test for pre-created users when DJANGAE_CREATE_UNKNOWN_USER is False
- Moved auto_create/admin check to allow pre-created users to be fetched as they would have been pre-0.9.4
PR checklist:
- ~~Updated relevant documentation~~ N/A
=> Allow precreated users to login when DJANGAE_CREATE_UNKNOWN_USER is False

CHANGELOG.md
#684 was committed before the 0.9.5 release but was not merged until afterwards, and hence the CHANGELOG entry ended up in the wrong section.  This fixes that.
=> Move changelog entry for #684 from 0.9.5 to 0.9.6.

testapp/install_deps.py
We've recently ran into problems unzipping the django release to get tests. I've changed our install_deps code to use the tarfile we use to install django instead.
=> Extract tests from the tarball instead of ithe zipfile

CHANGELOG.md, djangae/db/constraints.py, djangae/tests/test_connector.py
This fixes a bug where, if your model had more than one unique or unique_together constraint, a violation of one of those constraints could raise an IntegrityError which blamed the violation on the other constraint.
PR checklist:
=> Fix unique constraint violation message

CHANGELOG.md, djangae/contrib/gauth/common/models.py, djangae/contrib/gauth/common/validators.py, djangae/fields/__init__.py, djangae/tests/test_db_fields.py
Fixes #97.
- Adds a `CharOrNoneField` (which is required because a normal `CharField` will always set empty value to `""` instead of `None` when saved via a form (even with `blank=True, null=True, default=None`).
- Swapped `GaeAbstractBaseUser.username` to use this new field.
- Job done!
=> Allow user pre creation in admin

CHANGELOG.md, djangae/apps.py
- Prevents the contenttypes warning unless we're running on the appengine backend
PR checklist:
=> Fix contenttypes warning

djangae/apps.py
- Use model class rather than string when using db_for_read
PR checklist:
Apparently the default Django router does, but it's not documented that custom routers
need to support strings, only model classes.
=> Don't rely on db_for_read accepting strings

djangae/forms/fields.py
The `ValidationError` exception is not imported in the file, it can be reached from `forms`.
- Fixes import error.
=> Fix `ValidationError` import error in JSON field.

CHANGELOG.md, testapp/install_deps.py
Tests work with non-master & non-stable versions of Django.
- allow running tests when we test with alpha versions of Django.
PR checklist:
=> Dev django tests

docs/storage.md
=> Fix "accessible" typo in storage docs markdown

CHANGELOG.md, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/query.py, djangae/db/utils.py, djangae/tests/test_connector.py
Fixes #707.
- Fix a random test
- Fix the issue and bit of cleanup 
PR checklist:
=> Fix truncating microseconds on time and datetime fields

CHANGELOG.md, djangae/tests/test_connector.py
`test_ordering_on_sparse_field` tests the order in which objects are returned when the field that is being ordered on is missing.  It correctly checks that the objects with a missing value are returned before objects *with* a value, but it also expects the objects with a missing value to come back in a specific order.
This change removes the ambiguity of the ordering of items with a `color` value of `None`.
PR checklist:
=> Change `test_ordering_on_sparse_field` to avoid intermittent failure.

CHANGELOG.md, djangae/settings_base.py
Fixes #421 
- Change the ALLOWED_HOSTS default
PR checklist:
Google takes care of defending against host header attacks and having this fixed at
any other value has caused confusion when deployed apps return 400 responses
=> Change the default for ALLOWED_HOSTS to '*'

CHANGELOG.md, djangae/storage.py, djangae/tests/test_storage.py
- Generate a correct filename when using an empty upload_to on GCS
PR checklist:
=> Fix a bug when using an empty upload_to on a filefield on GCS

docs/fields.md
Hi,
This change fixes a mistake in the documentation for JSONField, where it currently says:
> Otherwise, conversation to/from JSON
http://djangae.readthedocs.io/en/latest/fields/#jsonfield
Hope this helps,
David B.
=> Changed "conversation" to "conversion" in docs for JSONField.

CHANGELOG.md, djangae/contrib/gauth/common/backends.py, djangae/contrib/gauth/common/models.py, djangae/contrib/gauth/middleware.py, djangae/contrib/gauth/tests.py, docs/gauth.md
Fixes #everything.  This will definitely not come back and bite me again.
Hopefully this removes all issues around the uppercase vs. lowercase differences in email addresses in Gauth.  So now:
* Neither the case of the email address of pre-created `User` object nor the case of the email address of the Google that a pre-created user logs in with make any difference.
* Email addresses are stored case sensitively, so that sending emails to people always works.
* Email addresses are forced to be unique on a case-insensitive basis, so:
- You cannot create _a@example.com_ and _A@example.com.
- In the rare case where the email address on a Google account changes and the original email address moves to a different Google account, it can change case when it moves and we will still handle it.
* All …
=> Fix user email case sensitivity once and for all

djangae/db/transaction.py
Previously, if there was an error in `_do_enter` then `_do_exit` would still be called.  And given that in the `AtomicDecorator`, `_do_exit` relies on things that `_do_enter` does, this means that another error would be raised in `_do_exit`, and the original error from `_do_enter` would never be seen, making debugging extremely difficult.
This change doesn't actually alter the functionality, but it might help us to debug a rare edge case issue that we're seeing where `state.transaction_started` raises an `AttributeError` in `_do_exit`, which is likely being caused by an error in `_do_enter` which we currently can't see.
=> Change the flow of try/exept in `ContextDecorator`.

CHANGELOG.md, djangae/fields/counting.py, djangae/tests/test_db_fields.py, docs/fields.md
Fixes #723.
- allow passing `on_change` callback function to `ShardedCounterField`
- call callback function when counter was changed (on `increment`, `decrement` and `reset`)
PR checklist:
=> 723 on change sharded counter

djangae/contrib/gauth/common/models.py, djangae/contrib/gauth/tests.py
Fixes the second thing that I broke in #722.
- See title.
PR checklist:  
(I'm not adding this to the changelog and am going to pretend that this was all done as part of #722.)
=> Fix bug where existing User objects wouldn't validate due to email unique constraint not excluding self.

CHANGELOG.md, README.md, runtests.sh, testapp/install_deps.py
Fixes #727.
* install_deps.py no longer installs the SDK every time, even when it exists.  It now only installs it if it doesn't exist or if you pass `--install_sdk`.
* install_deps.py now looks for an `SDK_VERSION` environment variable to allow easy installation of a different SDK version.
* runtests.sh now accepts an `--install_deps` flag so that you don't have to delete the App Engine SDK in order to get `install_deps` to be run, thus allowing the `DJANGO_VERSION=1.8` thing to work.
* Updated README to give correct instructions.
PR checklist:
=> Make various fixes to `runtests.sh` and `testapp/install_deps.py`.

CHANGELOG.md, djangae/db/utils.py
Fixes - circular import
- Inline some imports in djangae.db.utils to prevent circular import errors
PR checklist:
This should hopefully help prevent further import issues as now all imports that go deeper
into the .db.appengine package are inlines so import .db.utils should be safe.
=> Inline imports in djangae.db.utils to fix circular imports

djangae/contrib/contenttypes/models.py
I'm not sure exactly when this edge case happens, but it showed up when I tried to run Wagtail on Datastore ;) 
Wagtail is trying to do this: 
`ContentType.objects.get_for_models(*form_models).values()`, where `form_models == []`
Djangae blows up on this line: `self._store.queried_models |= set(models or [])` in `_update_queries` because `queried_models` doesn't exist on `self._store`: 
```
AttributeError at /admin/
'thread._local' object has no attribute 'queried_models'
```
=> Fix edgecase in SimulatedContentTypeManager

CHANGELOG.md, djangae/contrib/mappers/pipes.py
In the call to `set_status` after kicking off a Mapreduce we use the original
BASE_PATH instead of our own custom one when setting the console URL
for the pipeline. This breaks the pipelines status UI as it uses this
value to link to console URL of child pipelines.
=> Fix incorrect console URL stored in Mapreduce status entity.

CHANGELOG.md, djangae/db/backends/appengine/commands.py
Fixes #740.
- This avoids Django Debug Toolbar (which is the only thing these methods exist for) getting a UnicodeDecodeError when a query contains a non-ascii character.
PR checklist:
- N/A Updated relevant documentation
- N/A Added tests for my change
=> Change `lower()` methods of DB commands to return unicode instead of str

CHANGELOG.md, djangae/test.py, djangae/tests/test_test.py
Fixes #[742].
The internal testing function that gets a specific test stub task queue flushed all task queues instead of just the one specified. This caused a bug in `process_task_queues` where new tasks createdwhile processing a queue that do not belong to that queue would be flushed, and therefore never have a chance to execute.
=> Stop _get_queued_tasks flushing task queues other than the one specified

CHANGELOG.md, djangae/contrib/contenttypes/migrations/0001_patch_contenttypes_migrations.py, djangae/contrib/contenttypes/models.py, djangae/contrib/contenttypes/tests.py
- Fixes lots of small issues (missing imports, missing repopulation etc) around SimulatedContentTypeManager
- `get_or_create` now uses `create` method on create and doesn't raise an error anymore
- `create` method no longer does `get` first. Thought that's what it really should do. 
- Adds ability to pass `model` into SimulatedContentTypeManager
- Adds migration to patch ContentType manager in migrations as well
- Adds basic test suite.
PR checklist:
- Updated relevant documentation - n/a
=> SimulatedContentTypeManager improvements

CHANGELOG.md, djangae/contrib/contenttypes/migrations/0001_patch_contenttypes_migrations.py
Recently we added a clever hack to patch our simulated contenttypes manager even when
running migrations. This was necessary to get Wagtail working on GAE.
Our hack works by creating a migration which is a dependency of everything, however when calculating
the app list we were taking into account apps which didn't even have migrations. This commit
fixes that by ignoring apps which don't have a migrations module, or have on without files.
PR checklist:
=> Don't depend on apps which don't have migrations.

djangae/contrib/contenttypes/migrations/0001_patch_contenttypes_migrations.py
Improves the fix in #747.
In djangae.contrib.contentypes we inject our migration as a dependency of every other app's migrations, excluding ones which don't have migrations.  This change improves that excluding to cover apps which have a 'migrations' folder but with an `__init__.py` file but which don't actually have any migrations files.
Not updating the CHANGELOG as it's essentially part of the previous entry.
PR checklist:
=> Improve contenttypes migration dependency skipping

CHANGELOG.md, djangae/contrib/security/management/commands/dumpurls.py, djangae/management/commands/runserver.py
Fixes #749 .
- Cleaned up unused imports in Djangae's dumpurls command.
- Updated Djangae's runserver command to use the argparse way of adding arguments (which also fixes a RemovedInDjango110Warning deprecation message at startup).
This branch was forked from the v0.9.7 tag because I thought it would be good to push a new release with this fix, since that version advertises support for Django 1.10 but the bug prevents one running Djangae's local development server.
David B.
=> Use argparse for runserver

CHANGELOG.md, djangae/core/management/__init__.py, djangae/sandbox.py, docs/sandbox.md
Additional arg `--application` to override the application used in app.yaml, or where app.yaml does not specify an application.
=> Adds ability to override the application to run remote commands against.

CHANGELOG.md, djangae/contrib/security/commands_utils.py, djangae/contrib/security/tests.py
Previously, when running the `dumpurls` management command, it would error with `AttributeError: 'module' object has no attribute 'views'` because `admindocs.views` had not been imported.
This fixes that.
PR checklist:
- [-] Updated relevant documentation
=> Fix dumpurls

CHANGELOG.md, djangae/mail.py, djangae/tests/test_mail.py
Fixes #758.
- Added basic tests for the Djangae email backends.
- Slightly refactored code in the email backend to avoid a bit of duplicated code.
- Added logging of the 'from' address when App Engine rejects it with `InvalidSenderError`.
PR checklist:
- [-] Updated relevant documentation
=> Log invalid sender address

CHANGELOG.md, djangae/storage.py
Fixes #748 
Changed the cloud storage url method so that it gets the serving url. This now returns the correct path for images, and also makes use of the cache which stores the serving urls.
=> Use serving url for Cloud Storage images

CHANGELOG.md, djangae/storage.py, djangae/tests/test_storage.py
Fixes one of the side effects of #763, which is that calling `get_serving_url` causes a Datastore read, and therefore if you access `my_model_instance.image_field.url` inside a transaction it adds an entity group to that transaction.
- In both the `CloudStorage` and `BlobstoreStorage`, wrap calls to `get_serving_url` in `transaction.non_atomic`.
PR checklist:
=> Make calls to get serving url non transactional

CHANGELOG.md, djangae/storage.py, djangae/tests/test_storage.py
This PR fixes fetching url in CloudStorage for non-image files. 
- fix `CloutStorage.url` method to deal with image as well as non-image files
- regression test added
- rename `_get_or_create_cached_serving_url` into `_get_or_create_cached_blob_key_and_info` to reflect what actually the function does
PR checklist:
=> Serving url tranformation error

CHANGELOG.md, djangae/storage.py, djangae/tests/test_storage.py
url() method was not handling big files (>32MB) and broke when the `get_serving_url` was throwing `LargeImageError`
- catch `LargeImageError` in try clause when we attempt `get_serving_url` 
PR checklist:
=> Handle LargeImageError in BlobstoreStorage.url()

djangae/blobstore_service.py, djangae/contrib/consistency/consistency.py, djangae/contrib/contenttypes/models.py, djangae/contrib/locking/views.py, djangae/contrib/mappers/readers.py, djangae/contrib/security/middleware.py, djangae/contrib/uniquetool/models.py, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/indexing.py, djangae/db/backends/appengine/parsers/base.py, djangae/db/backends/appengine/query.py, djangae/db/constraints.py, djangae/mail.py, djangae/tests/test_mail.py, djangae/utils.py, djangae/views.py
Hi,
This pull request changes Djangae to use a named logger. The idea is this should make it simpler to configure logging, specifically when you want to suppress Djangae's messages.
It also removes and updates some existing named loggers so that they work the same as all the new ones (the DJANGAE_LOG variables).
One test broke because of these changes because it was testing that the global logger was called.
David B.
=> Use a named logger

CHANGELOG.md, djangae/db/backends/appengine/caching.py, djangae/tests/test_caching.py
Fixes #783 .
- Fix bug where entities were still fetched from memcache when deleting them within a transaction.
- Don't add entities to the cache.
PR checklist:
=> Fixes for DJANGAE_CACHE_ENABLED=False

CHANGELOG.md, djangae/contrib/locking/views.py, djangae/contrib/mappers/defer.py, docs/mappers.md
Fixes #790.
* Fixes a bug where if we hit DeadlineExceededError when doing the sharding, we would redefer but then not `return`, so the sharding task would fail and be retried, thus duplicating the sharding task(s).  In other words, if we couldn’t defer all the shards in one go, we would get stuck in an exponentially-expanding cycle of redefering the first X shards.
* The sharding tasks now redefers itself, (hopefully) _before_ hitting DeadlineExceededError, for a better chance of a successful redefer.
* Now orders the querset by PK and uses `filter(pk__gt=x)` rather than slicing.  This avoids an issue where the slicing would cause us to use more and more memory the further we got through the queryset, eventually hitting the App Engine …
=> Defer iteration fixes

LICENSE.md, setup.py
`./LICENCE.md` is infact the BSD 3-Clause License and not the MIT licence as defined in setup.py
* Add the title to the license file
* Update setup.py from MIT to BSD
- 
- 
- 
PR checklist:
=> Add BSD licence header and update setup.py

CHANGELOG.md, djangae/db/caching.py
Fixes #793 
- Use functools.wraps in the disable_cache decorator
PR checklist:
=> Use functools.wraps in the disable_cache decorator

djangae/management/commands/runserver.py, djangae/sandbox.py
Fixes #797.
- workaround for an incorrect version number in SDK 1.9.49 (it's 0.0.0 until issue: https://code.google.com/p/googleappengine/issues/detail?id=13439 will be fixed)
- change behavior of Djangae's implementaton of `skip_ignored_dirs` to work with SDK versions below and above 1.9.49
=> 1 9 49 sdk temporary fix

djangae/db/backends/appengine/commands.py, djangae/tests/test_connector.py
Doesn't fix #775, but fixes a similar issue:
We currently raise an exception that the Commands don't work with the `%` operator, because Django is trying to run `sql % params` where sql is our SelectCommand class.
=> Stoping exceptions when django tries to call  on our queries. Fixes #775

CHANGELOG.md, djangae/db/backends/appengine/base.py, djangae/test_runner.py, djangae/tests/test_connector.py
Fixes #800.
- Set the bulk_batch_size to MAX_ALLOWABLE_QUERIES
- Skip some Django test which expect a certain number of queries to run
PR checklist:
=> Limit the batch size when collecting objects for deletion

CHANGELOG.md, djangae/contrib/contenttypes/models.py, djangae/contrib/contenttypes/tests.py
Django models do not contain a `_deferred` attribute anymore, and instead they are part of the `models.DEFERRED` list.
=> Django 1.10 models do not have a _deferred attribute

CHANGELOG.md, djangae/db/backends/appengine/parsers/version_18.py, djangae/tests/test_connector.py
Fixes #746
- Adds a test for running a filter with an empty Q()
- 
- 
PR checklist:
=> Prove that empty Q() filters don't cause an error. Fixes #746

CHANGELOG.md, djangae/db/backends/appengine/parsers/base.py, djangae/tests/test_connector.py
Fixes #771 
- Adds a test to prove that .none().filter() doesn't explode like it used to
PR checklist:
=> Fix chaining none

CHANGELOG.md, djangae/db/backends/appengine/commands.py, djangae/tests/test_connector.py
- Fixes a bug where only("pk") wouldn't result in a keys_only query
PR checklist:
=> Fix keys only

CHANGELOG.md, djangae/contrib/locking/urls.py, testapp/testapp/urls.py
`django.conf.urls.patterns` is removed in django>=1.10, this removes the last remaining reference to it.
=> 'patterns' is deprecated in django 1.8-1.9 and removed in 1.10

CHANGELOG.md, djangae/sandbox.py
- Properly cleans up the App Engine stubs when the local sandbox shuts down. Search indexes are now saved after management commands and the shell.
PR checklist:
=> Properly shut down the search stub in the local sandbox

CHANGELOG.md, djangae/contrib/gauth/models.py, djangae/contrib/gauth_datastore/apps.py
Fixes #836 and #837 
- Fixes a bug in the permission creation code in gauth_datastore
- Fixes a bug where username would be set to 'None' rather than None in some cases
PR checklist:
=> Various gauth fixes

CHANGELOG.md, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py
This results in a number of improvements/changes:
- Queries are now fetched in cursor.execute() not during iteration which is more like other backends. This has the nice side-effect that Django Debug Toolbar now correctly shows query times
- Results are not wrapped in generators, making tracebacks from Djangae/AppEngine much more readable
- SelectCommand.execute() now returns the number of returned results, so cursor.rowcount is correctly set
- Transforms which are applied to entities are now outside _fetch_results() making the code lots more readable, and also makes profiling easier
- Performance should be marginally improved due to fewer variables / function calls
PR checklist:
=> Clean up the result fetching code

CHANGELOG.md, djangae/contrib/mappers/defer.py, djangae/contrib/mappers/tests.py, docs/mappers.md
These changes allow `defer_iteration` to work with querysets that already have inequality filters. This fix was made by Ola (the test as well), but I had to make a new branch and commit the changes myself as I had messed it up while updating the docs and the changelog.
Although, looking at recent changes, it seems that slicing was intentionally removed as it would cause memory leaks, so not sure if this fix is the right one.
=> Inequality filter with defered iteration

CHANGELOG.md, djangae/storage.py
Fixes a bug when appstats is combined with the CloudStorage backend. Also reduces RPC calls.
- Cache the default bucket name the first time it is accessed (globally, so per-instance)
- Make CloudStorageBackend.bucket lazy (fixes appstats infinite loop bug)
- Allow passing a callable as 'bucket'
PR checklist:
=> Cache default bucket

CHANGELOG.md, djangae/contrib/security/middleware.py
Django middleware changed in 1.10. See more [here](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware)
=> Updated AppEngineSecurityMiddleware to work with Django >= 1.10

djangae/forms/fields.py
* there is a chance that if we use custom widgets for the field, we
might end up with non-string value, which is wrong. This assert will
help identify potential issues. JSONFormField expects text or None only
and if we provide anything else (i.e. dictionary) we will have assertion
error raised very quickly.
=> Assert that value in JSONFormField is a string or None.

CHANGELOG.md, djangae/fields/__init__.py, djangae/tests/test_db_fields.py
Fixes #850 
- Fixes a bug where the Djangae CharField would get its validators overridden
PR checklist:
=> Allow additional validators to be specified on djangae.fields.CharField

CHANGELOG.md, djangae/fields/related.py, djangae/tests/test_db_fields.py
Fixes #851 
- Fixes a bug where where entries in RelatedSetField and RelatedListField weren't being converted to the same type as the primary key of the model
PR checklist:
=> 851 ensure related fields store pks as integers

CHANGELOG.md, djangae/checks.py
Django 1.10 introduced a new MIDDLEWARE setting, and session_csrf works
fine with it. This check will work with pre-1.10 projects which don't
have the MIDDLEWARE setting defined at all, with 1.10 projects which
use MIDDLEWARE in place of MIDDLEWARE_CLASSES, and with 1.10 projects
which use MIDDLEWARE_CLASSES but not MIDDLEWARE (in which case the
default for MIDDLEWARE is `None`).
This fixes #857.
=> Changes the session_csrf security check to check the MIDDLEWARE setting.

djangae/checks.py
This was supposed to be handled already by using `getattr`, but I was
totally thinking of how `{}.get('foo')` returns `None` if a key is
missing, whereas `getattr(obj, 'foo')` will raise AttributeError if
you don't specify a default.
Fixes #861.
=> Guard against no MIDDLEWARE setting when checking for session_csrf.

djangae/checks.py
- Now that we're specifying a default in the call to `getattr`, we no longer need to use the or operator to provide a default list. 
PR checklist:
=> Remove redundant default using or operator

CHANGELOG.md, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py, djangae/settings_base.py, djangae/test.py, djangae/test_runner.py, docs/installation.md
Fixes #849 .
- The slow startup performance for some projects appeared to be down to the real search stub being loaded before the test version. We've changed the way that the testbeds & stubs are being setup, by adding a new test runner which will be used by default. 
- These changes also highlighted an issue with how we reserve IDs. This was a long standing sporadic issue, which occurred every time the tests were run after the new changes to the test bed setup & tear down.
PR checklist:
=> 849 tests incorrectly load search indexes

CHANGELOG.md, djangae/contrib/pagination/tests.py
Fixes #465 
- Added a test to prove that the ordering specified on a model's `_meta` is used for pagination, when no custom order has been specified on the query set.
PR checklist:
=> Added a test to prove the model meta ordering is used for pagination

CHANGELOG.md, djangae/core/management/__init__.py, djangae/tests/test_management.py, docs/sandbox.md
Fixes #338
- Allow for the sandbox argument to be at any position in the args list, for the call to the management command.
PR checklist:
=> improve sandbox argument passing

CHANGELOG.md, djangae/environment.py, djangae/tests/test_environment.py, docs/environment.md
Adds a `@task_or_admin_only` decorator to `djangae.environment` to allow restricting views to tasks (including crons) or admins of the application.
PR checklist:
=> Add a `task_or_admin_only` view decorator to djangae.environment.

CHANGELOG.md, djangae/settings_base.py, djangae/storage.py, docs/storage.md
Although this means that the cloudstorage library must be available, it's a far better choice
for a future-proof backend, especially for new projects. If you still require the Blobstore just
override the DEFAULT_FILE_STORAGE setting.
Fixes #870 
- Switches the default storage backend from Blobstore to Cloudstorage (meaning 'cloudstorage' is now a requirement although you can just override the default if you don't want it)
PR checklist:
=> Switch the default storage backend to CloudStorage. Fixes #870

CHANGELOG.md, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/dnf.py, djangae/db/backends/appengine/meta_queries.py, djangae/tests/test_async_multi_query.py, djangae/tests/test_connector.py, docs/db_backend.md
Fixes #875 
- Move meta queries into their own file
- Implement a multithreaded MultiQuery alternative which replaces the 30 query limit with a configurable one
- Switch to using the new MultiQuery exclusively
PR checklist:
=> Replace MultiQuery with our own version (AsyncMultiQuery)

CHANGELOG.md, djangae/db/backends/appengine/base.py, djangae/sandbox.py, djangae/test_runner.py, docs/sandbox.md
Fixes #879 
- Reset the in-context cache in `init_testbed()` rather than in the Datastore connector test methods
- Set up a minimal testbed in the test sandbox so that things don't die horribly if you try to access the Datastore before the test run (e.g. in settings.py)
PR checklist:
=> Test sandbox fixes

CHANGELOG.md, djangae/db/backends/appengine/caching.py, djangae/db/backends/appengine/context.py, djangae/db/backends/appengine/meta_queries.py, djangae/tests/test_utils.py, docs/db_backend.md
Fixes #886 
Fixes #831 (hopefully)
- Heavily optimise the context cache which was copying wastefully
- Add a memory limit to the context cache (configurable by `DJANGAE_CACHE_MAX_CONTEXT_SIZE`)
- Restrict the number of entities which are cached after a PK query (configurable with `DJANGAE_CACHE_MAX_ENTITY_COUNT`)
- Fix a typo in the `DJANGAE_MAX_QUERY_BRANCHES` setting lookup
This PR needs some tests for the `CacheDict` class (particularly around entity eviction), but I'm going on holiday so feel free to pick this up @adamalton  :)
PR checklist:
=> Improve caching performance

CHANGELOG.md, djangae/environment.py, djangae/tests/test_environment.py
This avoids an ImportError exception at startup. The sandbox pulls in
djangae.environment, and that was importing google.appengine.api before
the sandbox had a chance to put the SDK on the path (for those cases
where a project is using the location of dev_appserver.py to have the
SDK added to sys.path).
Fixes #899 .
PR checklist:
- [* ] Updated CHANGELOG.md
=> Moved import of Users API inside the view decorator.

djangae/test_runner.py
Some pr's are adding tests modules with `tests/something_tests` files. and this change is the easiest way we can include them while also matching our existing tests (which are mostly `tests.py` files)
=> Altering the default file pattern of our DiscoverTestRunner

CHANGELOG.md, djangae/contrib/gauth/settings.py, docs/gauth.md
[The docs say DJANGAE_CREATE_UNKNOWN_USER defaults to False][1]. This is not true.
[1]: https://djangae.readthedocs.io/en/latest/gauth/#authentication-for-unknown-users
- Updated docs for DJANGAE_CREATE_UNKNOWN_USER.
- Updated comments in Djangae's settings module for DJANGAE_CREATE_UNKNOWN_USER.
PR checklist:
- [*] Updated relevant documentation
- [*] Updated CHANGELOG.md
=> Updated docs and comments for DJANGAE_CREATE_UNKNOWN_USER

CHANGELOG.md, djangae/fields/iterable.py, djangae/fields/related.py, djangae/tests/test_db_fields.py
Fixes #881.
This may get superseded if #555 gets completed but it seemed worth fixing the short term problem.
- Fix issue where serialization of IterableFields resulted in invalid JSON
PR checklist:
=> Fix issue where serialization of IterableFields resulted in invalid JSON

CHANGELOG.md, djangae/test.py, djangae/tests/test_environment.py, djangae/tests/test_test.py
Fixes #914 
**NOTE: Contains #916**
- Allow controlling the error handling behaviour of process_task_queues
- Handle exceptions thrown by tasks as if they were thrown from inside Django (return an error response rather than propagating)
PR checklist:
=> Control task handling behaviour in process_task_queues

CHANGELOG.md, djangae/test.py, djangae/tests/test_environment.py
Fixes #915 
- Add task headers to os.environ when processing tasks in tests
PR checklist:
=> Fix os.environ task headers in tests

CHANGELOG.md, djangae/test_runner.py
Fixes #906 
- Don't initialize the images stub in tests if PIL isn't available
PR checklist:
=> Don't initialize the images stub if PIL isn't available

djangae/contrib/processing/mapreduce/helpers.py, djangae/contrib/processing/mapreduce/tests/helper_tests.py, djangae/contrib/processing/mapreduce/tests/helpers.py, docs/pipelines.md
Fixes #920 
- Allows _filters as an optional argument to map_entities which is passed down to mapreduce
- Adds namespace to `map_reduce_entities` which was documented, but didn't exist!
I haven't updated the changelog as this entire module is new.
PR checklist:
=> Allow passing filters to mapreduce

CHANGELOG.md, djangae/db/utils.py, docs/pagination.md, docs/release_notes/0_9_10.md
Fixes #872 
- Fixes outdated assumption of the valid length of a string key (1500 bytes is the actual limit, not 500)
- Doesn't truncate keys automatically, saving will now be an error
PR checklist:
=> Fix key length

CHANGELOG.md, djangae/contrib/backup/tests/test_utils.py, djangae/contrib/backup/tests/test_views.py, djangae/contrib/backup/urls.py, djangae/contrib/backup/utils.py, djangae/contrib/backup/views.py, docs/backup.md, testapp/testapp/settings.py
Adds a new contrib app to allow automatic backups to be configured.
This is basically a request handler which can be hit by a cron in order to call the datastore backup job provided by datastore admin.
The handler allows you to:
- Automatically backup all registered models without the need to manually update the backup URL when new models are added
- Allow the backup name and GCS bucket to vary based on the value in settings. For example, you may have a single codebase deployed to multiple apps (such as a staging environment) and want to back them all up to different GCS buckets or give them different names. Without this handler a backup URL would need to be static and I don't it'd be possible to back up any more than one app without manually altering the cron entry before deploying to …
=> Add djangae.contrib.backup app

djangae/contrib/gauth/backends.py, djangae/contrib/gauth_datastore/backends.py, djangae/contrib/gauth_sql/backends.py
Within the auth backends, the atomic function/decorator/context manager is stored as a class property (to abstract it for use with Django/Djangae implementation), which when called [here](https://github.com/potatolondon/djangae/blob/master/djangae/contrib/gauth/backends.py#L139) , is treated as a class method, and a class instance is passed as the first argument.
This causes it to fail, as the first argument is expected to be the db alias (`using`), to fix this, we could either return the atomic function from another function, or, as i have done here, wrapped it in `partial`, so it is treated as a standalone function, not a classmethod.
Also included @TysonRV 's import fix 
=> gauth backend fails to authenticate

CHANGELOG.md, djangae/checks.py, djangae/tests/test_checks.py
- Add IDs to system check errors
- Add tests for checks
- Fixed check that didn't always return a list
Without IDs on errors raised by Djangae checks there is no way to silence them. A few examples:
* The check for django-sessions-csrf is not required with Django 1.11 as the same functionality is now built-in
* The check for unsafe-* CSP directives should be silenced if you want to use CSP nonces, but also want to support IE 11
* To do this you need both nonces and `'unsafe-inline'` in your CSP directives, the latter being ignored by Firefox and Chrome when there is a nonce present
PR checklist:
- _n/a_ Updated relevant documentation
=> System check errors should have an ID

CHANGELOG.md, djangae/fields/computed.py, djangae/tests/test_db_fields.py, docs/fields.md
This allows computed fields to take the name of a method instead of a function object as the "computer" function.
The main benefit of this is that it allows the field to be pickled, even when using a method on the model class as the computer function.  Unbound methods on the class can't be pickled, so if you pass in a method directly into the field, you then can't pickle the field.
Fixes #968.
PR checklist:
=> Allow computed fields to take the name of a method

CHANGELOG.md, testapp/manage.py
Fixes #974.
- Do not emit logging output when running `manage.py test`
PR checklist:
- [N/A] Added tests for my change
=> do not emit logging output when running tests

CHANGELOG.md, djangae/contrib/security/tests.py, djangae/db/migrations/operations.py, djangae/tests/test_indexing.py
Fixes #976 .
- turn all `print()` calls in unit tests to `logging.debug()` calls
- silence all `print()` statements in command and other output when `test` is in `sys.argv`
PR checklist:
- [N/A] Updated relevant documentation
- [N/A] Added tests for my change
=> Replace print with logging

CHANGELOG.md, djangae/core/management/__init__.py, djangae/management/commands/runserver.py
Fixes #981
- Help text for all management commands is now working
PR checklist:
=> Fix broken `--help` in management commands

djangae/test.py
The recent change to `failure_behaviour` didn't change the default behaviour in TestCaseMixin so DO_NOTHING was overriding RAISE_ERROR when calling `process_task_queues` with no failure behaviour passed in.
=> Update TestCaseMixin to reflect change made to process_task_queues failure behaviour

CHANGELOG.md, djangae/compat.py, djangae/sandbox.py, djangae/wsgi.py
Fixes #964
- Add `djangae.compat` as a central place to handle module/package changes in SDK versions 
- Supporting caching of downloaded SDK versions
PR checklist:
=> Add `djangae.compat`

CHANGELOG.md, djangae/contrib/backup/tests/test_utils.py, djangae/contrib/backup/tests/test_views.py, djangae/contrib/backup/utils.py, djangae/contrib/backup/views.py, docs/backup.md, mkdocs.yml
Fixes #1004.
- The DJANGAE_BACKUP_GCS_BUCKET setting is optional. It defaults to
the project's default bucket with a suffix of 'djangae-backups',
e.g. 'myapp.appspot.com/djangae-backups'.
- The DJANGAE_BACKUP_NAME setting is optional. It defaults to
'djangae-backups'.
- Backups are created with a timestamp in the object name, e.g.
'myapp.appspot.com/djangae-backups/20171128-235900'.
- Updated docs (and fixed the docs config to include the backup docs).
=> Changed djangae.contrib.backup to be easier to use.

CHANGELOG.md, djangae/fields/language.py, djangae/tests/test_computed_collation_field.py
Fixes a TypeError exception when generating the value for ComputedCollationField
- Only conditionally convert a source value to unicode if it's not already
PR checklist:
=> Fix collation TypeError

CHANGELOG.md, djangae/fields/computed.py, docs/fields.md
* This is useful when working with apps with existing data sets / schemas, as attempting to add the ComputedBooleanField retrospectively will blow up.
Note - Didn't add a test as the `ComputedFieldMixin` mixin is already used extensively. 
PR checklist:
- [*] Updated relevant documentation
- [*] Updated CHANGELOG.md
=> Add a ComputedNullBooleanField

CHANGELOG.md, djangae/forms/fields.py, djangae/tests/test_form_fields.py
Fixes #1014.
- Make `value_from_datadict` in `forms.fields.ListWidget` return None when the value provided is `None` as the existing comment describes. This prevents an exception when `save()` is called on a `ListWidget` whose value is `None`.
PR checklist:
=> Make value_from_datadict return None if value is None. Fixes #1014

CHANGELOG.md, djangae/contrib/sleuth.py, djangae/tests/test_sql_formatting.py
- Updates the bundled sleuth.py to latest
- Removes a reference to the "mock" library which was used in a single test (?)
PR checklist:
=> Update sleuth to the latest version, remove mock

djangae/contrib/common/middleware.py
Fixes issue with contrib.common.RequestStorageMiddleware not being compatible with Django 1.10 when using the new MIDDLEWARE setting.
=> Made ``contrib.common.middleware`` Django 1.10 compatible.

CHANGELOG.md, djangae/db/backends/appengine/caching.py
Fixes broken memcache caching if the default DATABASE namespace is set to ''.
This matches the default namespace returned by App Engine.  Otherwise, you
end up in a situation where the getter code uses a (memcache) key with a stringified
None, but the setter code is using a stringified ''.  i.e.  You can't
retrieve anything from the cache.
An alternate fix would be to fix the add_... code to do the same or None check
- Changes default namespace used by memcache to '' instead of None
This change takes our cache hit rate from ~8% up to >90% in testing.  I don't have historical cache hit data, but I suspect this was made worse by the [workaround](https://github.com/potatolondon/djangae/issues/789#issuecomment-264225096) for issue #789
=> Use '' instead of None for an unset namespace.

CHANGELOG.md, djangae/core/management/__init__.py
Priority:
1) "managepy" (default)
2) value from sandbox_overrides
3) --app_id flag
This also fixes the issue where if there was no application: in the app.yaml
(i.e.  using gcloud) the default app_id will be "None", which is not valid
as a datastore namespace because it's not all lowercase.
Fixes #1008.
Helps with #972.
=> Allow customizing the app_id and set a reasonable default.

CHANGELOG.md, djangae/checks.py, djangae/views.py, docs/security.md, docs/sessions.md
- Makes the CSRF session check respect the newish `CSRF_USE_SESSIONS` setting in Django
- Locks down the clearsessions view to tasks or admins only
PR checklist:
=> Security tweaks

CHANGELOG.md, djangae/utils.py
- This increases the min wait time for retry from 100ms to 375ms as the previous value caused more problems than it solved (increased contention and likelihood of transaction failure)
- The value is now overridable through the `_initial_wait` kwarg.
This is a stop-gap improvement as `retry()` needs a proper cleanup and tests. I haven't added documentation as the function is currently undocumented and will be undergoing API change soon so it's probably best not to advertise it too much now!
PR checklist:
=> Tweak retry time

CHANGELOG.md, djangae/db/backends/appengine/formatting.py, djangae/tests/test_sql_formatting.py
Fixes #1027 
- Test to trigger unicode error.
- Small change to how a unicode value is quoted for the SQL representation.
PR checklist:
=> SQL representation unicode error

CHANGELOG.md, djangae/fields/related.py, djangae/tests/test_db_fields.py, testapp/testapp/routers.py, testapp/testapp/settings.py
Fixes #1034.
- Fix cross-database support for `RelatedSetField` and `RelatedListField`.
- Introduce `testapp.routers.TestRouter` so that models in tests can explicitly choose a database.
PR checklist:
=> Fix cross-database support for RelatedSetField and RelatedListField

CHANGELOG.md, djangae/contrib/backup/tests/test_views.py, djangae/contrib/backup/urls.py, djangae/contrib/backup/views.py
Fixes #1038 
- Locks down the backup creation view to admins and tasks
- Fixes the URL to match the documentation
PR checklist:
=> Lock down the backup view

docs/mappers.md
Hi,
This change updates the documentation for https://djangae.readthedocs.io/en/latest/mappers/ , adding a missing step for installation.
Dave
=> Clarified installation instructions for the Map Reduce contrib package.

CHANGELOG.md, djangae/db/migrations/mapper_library.py, djangae/tests/test_migrations.py
Fixes #1057 
- Fix the migration mapper's _get_range function to properly deal with strings
PR checklist:
=> Fix finding the largest range between string keys

CHANGELOG.md, djangae/environment.py, djangae/utils.py
Fixes #1055 .
The current logic allows one to have the SDK tools (dev_appserver.py, etc.)
on one's $PATH, and then Djangae works out where the SDK is installed and
adds it to sys.path, after which it is OK to import things from the SDK
modules.
But that got broke because `./manage.py runserver` indirectly loads this
module, which was pulling in things from the SDK. If you don't have the
SDK already already on sys.path, this would result in ImportError.
This fix moves the SDK imports inside the function (and adds comments which may or may not prevent this bug happening again).
=> 1055 import error

CHANGELOG.md, testapp/install_deps.py
Pip version 10 dropped support for the `--no-use-wheel` flag, which
meant that the test dependencies wouldn't install properly. This
change is compatiblie with pip versions 8 and 9 too (I didn't test
earlier versions).
Fixes #1063 .
=> Use `--no-binary :all:` when installing Django for tests.

README.md, docs/index.md
- Remove the (unmanned) Slack link
- Replace with the (usually manned) Gitter link
- Clean up the link section of the readme
PR checklist:
=> Remove slack

CHANGELOG.md, djangae/db/backends/appengine/base.py, djangae/db/backends/appengine/commands.py, djangae/db/backends/appengine/formatting.py, djangae/db/backends/appengine/query.py, djangae/tests/test_db_fields.py, djangae/tests/test_form_fields.py, djangae/tests/test_sql_formatting.py
Fixes #1075.
- Need to properly encode/decode utf8 in a couple places when generating sql
- Sql string literals should be single quoted (not double), and ints shouldn't be quoted at all
PR checklist:
- [N/A] Updated relevant documentation
=> fix a couple sql unicode bugs; and fix quoting of sql value literals

CHANGELOG.md, djangae/db/transaction.py, djangae/tests/test_transactional.py
Fixes a bug that occurs if you have a non_atomic() block, and delete something within it. The cache before the block would be restored and the deleted item would be returned in a subsequent .get()
- Add test to prove issue
- Fix the atomic decorator
PR checklist:
=> Fix a caching bug caused by the non_atomic decorator

CHANGELOG.md, djangae/checks.py, djangae/tests/test_checks.py
Reverts potatolondon/djangae#1101
This change breaks startup when deployed to App Engine. Reverting for now.
=> Revert "check google cloud sdk version on local server start"

djangae/db/transaction.py
This doesn't actually affect the behaviour because no other transaction will exist, we were just pointlessly continuing to loop.
Also removed `active_transaction = None` because all cases where we set this variable are now followed by a `break`, so if we get to this line then it will always be `None` anyway.
PR checklist:
=> Add a `break` statement into `current_transaction`

djangae/db/transaction.py, djangae/tests/test_transactional.py
This bug meant that if an exception that subclassed BaseException rather than Exception was raised during a transaction, the transaction (as far as it had got) was committed rather than rolled back.
Such exceptions include google.appengine.runtime.DeadlineExceededError.
Fixes #1107.
The commit in which this bug was introduced was `166a82255`.  That commit has not been included in an official release yet, and hence I haven't added a CHANGELOG entry for this fix, because the bug hasn't affected any actual release.
PR checklist:
=> Fix a bug with exception catching in the transaction decorator

djangae/db/migrations/mapper_library.py, djangae/db/migrations/operations.py, djangae/deferred.py
This is particularly useful if you use the Django LOGGING setting to
configure the levels for 'djangae.*' loggers. If you use plain
`logging.info(..)` then that uses the root logger, so would ignore
any settings the admin chose for 'djangae.*' loggers.
There's also a bunch of root logging calls in tests, I have ignored
those.
- 
- 
- 
PR checklist:
=> Changed some logging calls to use a named logger.

README.md
Also change the example for switching the DJANGO_VERSION to one which is more likely to be used.
We could switch the default to be 1.11, but I'll leave that for another day.
=> Fix statement in README about which Django versions Travis runs

.flake8, djangae/deferred.py, docs/deferred.md
Fixes #1139 
- Default the `_buffer_time` arg to `defer_iteration_with_finalize` to None
- If the `_buffer_time` is None, calculate the buffer time from the longest previous iteration
Note: I haven't updated the CHANGELOG as `defer_iteration_with_finalize` is a new function. I also have been unable to think of how to write a good test for this...
PR checklist:
=> Calculate buffer time

CHANGELOG.md, djangae/tests/test_utils.py, djangae/utils.py, docs/utils.md
Fixes #1149 
- Catch InternalError by default
- Re-raise original exception when retrying fails
- Log each error otherwise only the final error source will be shown
- Add an element of randomness to the retry time
- Increase the default initial wait time to 750 ms
PR checklist:
=> Improve retry

testprodapp/requirements.txt
This is just updating the Django version used in the testapp.
1.11.19 contains a security fix, so that should now be the minimum.
=> Update Django requirement to >=1.11.19

docs/gauth.md
The [current link](https://p.ota.to/blog/2014/2/google-multiple-sign-in-on-app-engine/) results in a 404, so I've replaced it with a link to the Medium article which appears to be its replacement.
=> Update "Google multiple sign-in on App Engine here" link URL

CHANGELOG.md, djangae/db/utils.py, djangae/fields/iterable.py, djangae/fields/related.py, djangae/tests/test_db_fields.py, djangae/tests/test_form_fields.py, docs/fields.md
Fixes #1017
- add new kwargs option "remove_duplicates" to ListField and RelatedListField
- fix some PEP-8 warnings 
PR checklist:
=> add new option remove_duplicates to ListField and RelatedListField

docs/consistency.md
Per v0.9.4, I've changed references from ensure_instance_included to ensure_instance_consistent and updated the associated deeplink.
=> Change ensure_instance_included to ensure_instance_consistent

djangae/db/backends/appengine/dnf.py
After determining the add_branch should be removed while resolving detect_conflicting_key_filter, we should stop trying to remove the add_branch. It doesn't matter how many times we confirm it should be removed, we should just remove it once to avoid the ValueError that occurs from trying to remove it again.
Fixes #1174.
- Add a `break` after removing the and_branch.
- It is possible that this doesn't address a deeper issue, in that maybe the issue is that more than 2 key lookup children were being added to the `and_branch`es that caused my problems. But objectively, looking at the bit of code in this for loop, the loop should be terminated after removing the `and_branch` from `node.children`. There is no reason to continue it.
PR …
=> break after removing add_branch

djangae/tests/test_query_transform.py
This tests that the bug reported in #1174 and fixed in #1175 is fixed.
PR checklist:
- [-] Updated relevant documentation
=> Add a test for DNF code that removes multiple different PK equality filters

CHANGELOG.md, djangae/contrib/backup/tasks.py
Fixes #1178 
- remove the (empty) `namespaceIds` option so that all datastore namespaces are included in the backup
PR checklist:
=> Include all namespaces in the backup

CHANGELOG.md, djangae/contrib/locking/models.py, djangae/contrib/locking/tests.py
Fixes #1187.
- Handle transaction errors when trying to acquire a lock
- Improved the locking retry countdown.
PR checklist:
@Kazade re #1187, not sure where you meant the independent arg should be added? `transaction.atomic` doesn't support that specific one as far as I know.
=> Improve locking transaction

CHANGELOG.md, djangae/contrib/backup/tasks.py, djangae/contrib/backup/tests/test_tasks.py, djangae/contrib/backup/tests/test_views.py, djangae/contrib/backup/views.py, docs/backup.md
Fixes #1184
* Update the `django.contrib.backups` app to use db_table when determining which datastore kinds to backup for a model. 
* Fix some function naming to use kind when operating/returning kinds.
* Updates tests and fix false positive.
PR checklist:
=> Fix backup ignoring models that override table name using db_table

CHANGELOG.md, djangae/contrib/backup/tasks.py, djangae/contrib/backup/tests/test_tasks.py
Fixes #1192 
The datastore export API returns an error when passing the same kind more than once. This PR de-de-dupes the list of kinds before doing the call.
PR checklist:
=> De-dupe kinds before they are passed to the datastore export API

CHANGELOG.md, djangae/contrib/locking/models.py, djangae/contrib/locking/tests.py, docs/locking.md
-  Adds a max_wait_ms argument to Lock.acquire
PR checklist:
=> Add max_wait_ms to Lock.acquire

djangae/tasks/__init__.py
- App Engine credentials aren't available on Python 3 so don't specify any credentials
PR checklist:
=> Don't try to use appengine credentials

djangae/sandbox.py
Fixes #1200 
- Add `--target-port` when starting the tasks emulator
- Allow to configure manually
- If configured automatically, try to detect from `runserver` invocation
=> Add target-port when starting tasks emulator

CHANGELOG.md, djangae/settings_base.py, docs/installation.md
The database cache doesn't work since it's not using django models but executing raw sql queries.
This PR replaces it with `FileBasedCache` (which can be used with the new standard environment).
PR checklist:
=> Cache to file

djangae/contrib/security/decorators.py, djangae/tests/test_views.py, djangae/urls.py, djangae/views.py, docs/installation.md, test_settings.py
Fixes #1211 
- Fixes broken decorator
- Updates djangae.urls to use modern Django path() rather than url()
- Removes the unused internalupload view
PR checklist:
=> 1211 invalid decorator

djangae/contrib/security/middleware.py
Fixes #1196
- Remove import of urlfetch which doesn't exist in the Python 3 runtime
PR checklist:
=> Remove appengine import. Fixes #1196

CHANGELOG.md, djangae/processing.py, djangae/tests/test_defer_iteration.py, testapp/testapp/routers.py, testapp/testapp/settings.py
Fixes #1210.
- Added SQL support for defer_iteration_with_finalize
- Added tests and a new SQLite database to testapp
- This was branched from `1.x`, but it would work on the `master` branch too if the DB connection detection mechanism is compatible with the most recent changes in Djangae on `master`  (which I'm not familiar with). 
- Tested with Django 1.11
PR checklist:
Not sure where to add the item in the changelog file exactly as it doesn't look up to date.
=> Defer iteration with finalize for sql

djangae/sandbox.py, djangae/tasks/__init__.py, docs/deferred.md, tox.ini
- Passes the `--queue-yaml`, `--queue-yaml-project`, and `--queue-yaml-location` args to the task emulator
PR checklist:
=> Pass queue.yaml to the task emulator

djangae/sandbox.py, djangae/storage.py, djangae/test.py, setup.py, tox.ini
Configure env variable when starting emulators
Fixes #1230
- Make sure client uses the correct project id
- Configure the project id in `start_emulators`
- 
PR checklist:
=> Make sure project is passed to storage client

CHANGELOG.md, djangae/environment.py, djangae/tasks/deferred.py, djangae/tasks/tests/test_deferred.py
Cloud Tasks run on the default GAE version, by default. I suggest we change the default behaviour to route tasks to the GAE version which created the task. This will ensure that the deferred task exists.
When calling `deferred.defer()`, allow the user to control [task routing](https://cloud.google.com/tasks/docs/reference/rest/v2/AppEngineRouting) using the `_service`, `_version`, and `_instance` parameters.
=> Handle task routing using defer

CHANGELOG.md, djangae/sandbox.py
- allow caller to specify the emulator ports to use
- allow multiple Djangae apps to run on the same machine, each with its own emulators (on separate ports)
=> Customise emulator ports

CHANGELOG.md, djangae/contrib/backup/tasks.py
- fix backup task when running in production
- using `app_engine.Credentials` on GAE Python 3 raises an error `The App Engine APIs are not available.`
=> Fix backup task credentials

djangae/tasks/deferred.py, djangae/tasks/tests/test_deferred.py, docs/deferred.md, setup.py
- Implements the _transactional flag to defer similar to what existed in the Python 2 App Engine runtime
- Adds a _using argument so you can choose which connection to tie transactionality to
- Defaults _transactional to True if inside an atomic block, or False otherwise (which is the path of least surprise)
PR checklist:
=> Implement transactional defer

CHANGELOG.md, djangae/sandbox.py
- add parameter to `start_emulators` function to specify the datastore emulator `--data-dir` parameter
=> Specify the datastore emulator data-dir parameter

CHANGELOG.md, djangae/environment.py, djangae/tasks/deferred.py, djangae/tests/test_environment.py
- remove `environment.queue_name()` function, use `environment.task_queue_name()` instead
- update `environment.task_queue_name()` to return `default` if we're in a task and a queue name is not set, otherwise return `None`
- update `djangae/tasks/deferred.py` to handle the case where a queue name is not set
=> Update environment.task_queue_name() return values

tox.ini
0.5.0 had a bug that would prevent process_task_queues from submitting tasks
correctly.
=> Update gcloud-tasks-emulator to 0.5.1

djangae/contrib/googleauth/backends/__init__.py, djangae/contrib/googleauth/backends/iap.py, djangae/contrib/googleauth/backends/oauth2.py
- `_generate_unused_username` now being used in `oauth2.py`
- Profile object does not contain username - only userId, full name, given name, family name, image URL and email, so we won't create add char field `profile_username` to `AbstractGoogleUser`
PR checklist:
=> Generate username function now being used in OAuth flow

djangae/sandbox.py
Fixes #1279 
- Pass project_id to datasatore start command
PR checklist:
=> Pass project-id to datastore start #1279

djangae/sandbox.py
Fixes #1282
- when starting a new emulator, use the first available port if not pass explicitly 
- Raise an exception if the port is passed and not available
PR checklist:
=> 1282 sandbox

djangae/contrib/googleauth/backends/iap.py, djangae/contrib/googleauth/backends/oauth2.py, djangae/contrib/googleauth/tests/test_iap.py, djangae/contrib/googleauth/tests/test_oauth.py
Fixes #1272 
- Call set_unusable_password() on users created via IAP or OAuth
PR checklist:
=> Make sure we call set_unusable_password() whenever we create a User

djangae/contrib/search/tests/test_query.py, djangae/sandbox.py
- Add a test to prove startswith searching with multiple tokens works as expected
- Lower the verbosity of the datastore emulator start up in the sandbox
PR checklist:
=> Add tests for startswith searching

djangae/contrib/search/__init__.py, djangae/contrib/search/fields.py, djangae/contrib/search/index.py, djangae/contrib/search/model_document.py, djangae/contrib/search/query.py, djangae/contrib/search/tests/test_indexing.py, djangae/contrib/search/tests/test_query.py, djangae/contrib/search/tests/test_searchable.py, djangaeidx.yaml
- Add index=False/True to search fields
- Implement null=False
- Make ModelDocument.instance_id index=False
PR checklist:
=> Non indexable search fields

djangae/contrib/search/index.py, djangae/contrib/search/tests/test_query.py
- Adds the ability to pass an order_by field to index.search()
PR checklist:
=> Add the ability to order by a document field

djangae/contrib/googleauth/decorators.py, djangae/contrib/googleauth/middleware.py, djangae/contrib/googleauth/tests/test_iap.py, djangae/contrib/googleauth/tests/test_local_iap_middleware.py, djangae/contrib/googleauth/tests/test_middleware.py, djangae/contrib/googleauth/tests/test_views.py, djangae/contrib/googleauth/views.py
Make sure we do not show the consent screen to the user every time the oauth session expires.
If a django session exists, the prompt should not be shown, while it should otherwise (ie. to allow user to log with a different account).
PR checklist:
=> 1292 oauth consent screen

djangae/tasks/deferred.py, djangae/tasks/tests/test_defer_iteration.py, docs/deferred.md
Fixes #1207 
- Re-defer defer_iteration shards after 9.5 minutes consistently
- Make shard-index access thread-safe
PR checklist:
=> Better deferred shard handling

djangae/contrib/search/document.py, djangae/contrib/search/fields.py, djangae/contrib/search/index.py, djangae/contrib/search/query.py, djangae/contrib/search/tests/test_indexing.py, djangae/contrib/search/tests/test_query.py, docs/contrib_search.md
- Add `match_stopwords` as a kwarg to `search()`, defaults to True
- Index stopwords during search indexing
- Add a simple ranking algorithm to the search results by default
PR checklist:
=> Improve stopword handling

djangae/contrib/googleauth/middleware.py, djangae/contrib/googleauth/tests/test_middleware.py, docs/googleauth.md
Fixes #1303 
- By default, don't log out a Django session just because the oauth session became invalid
- Make this configurable via the `GOOGLEAUTH_LINK_OAUTH_SESSION_EXPIRY` setting
PR checklist:
=> Fix oauth expiry

djangae/contrib/search/model_document.py, djangae/contrib/search/query.py, djangae/contrib/search/tests/test_searchable.py, docs/contrib_search.md
- Fix partial token matching ranking
- Add ordered_ids as an optional kwarg to `qs.search(...)`
- Add `search_and_rank()` as a search queryset method
PR checklist:
=> Fix ranking of model querysets

djangae/tasks/deferred.py, djangae/tasks/tests/test_defer_iteration.py
- Fixes a bug which could cause instances to be skipped while iterating with defer_iteration_with_finalize
PR checklist:
=> Fix issue where entities may be skipped in defer_iteration_with_finalize

djangae/contrib/googleauth/backends/oauth2.py
we should set the username if it's not set.
Not having a username, breaks the AbstractGoogleUser save.
PR checklist:
=> Set username if none

djangae/contrib/googleauth/middleware.py, djangae/contrib/googleauth/tests/test_middleware.py
Fixes #1320 
Went a slightly different way than I described in the issue, and instead just moved the code from process_view -> process_request and used resolver_match to look up the handling
view.
- Perform authentication in process_request, instead of process_view
PR checklist:
=> Move everything into process_request

CHANGELOG.md, djangae/contrib/security/management/commands/dumpurls.py, djangae/contrib/security/tests.py
Fixes `dumpurls` command which fails for named views when the view contains one or more parameters.
- Fixes bug where `dumpurls` command would fail if a view linked to  a named url has a parameter.
PR checklist:
=> Use function to determine class based view info
