potatolondon/djangae

djangae/storage.py
djangae/templatetags/storage.py
djangae/tests.py

This just makes things nicer than just inheriting stuff from djangoappengine

Improve blob serving

---

djangae/contrib/gauth/tests.py

See commit comments for detailed banter.

Allow gauth tests to run with custom user

---

README.md
TODO.md
djangae/contrib/gauth/models.py
djangae/contrib/security/decorators.py
djangae/db/backends/appengine/commands.py
djangae/indexing.py

Hi.
I fixed some typos.
Thanks.

Fix some typos

---

djangae/db/backends/appengine/base.py
djangae/db/backends/appengine/commands.py
djangae/tests.py

Reusing some string handling for the query building code.

---

djangae/sandbox.py

Fixes the missing env variable that some appengine libraries (webapp) use to determine import paths

Sandbox fixes env

---

djangae/db/constraints.py
djangae/tests.py

Introduce a mixin to allow for validating iterable uniques.

---

djangae/contrib/mappers/pipes.py
djangae/contrib/mappers/readers.py
djangae/contrib/mappers/tests.py

More mapper functionality and tests including
> Dynamic model on pipeline init
> args and kwargs for the mapper function without any crazy pickle datastore madness

More mapper improvements

---

djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/dnf.py
djangae/tests.py

This PR makes a few more queries possible by filtering out PKs in memory in some specific situations

Allow excluding pk

---

djangae/contrib/mappers/pipes.py
djangae/contrib/mappers/tests.py
djangae/contrib/mappers/thunks.py

Using the proper pipeline class means proper setup, chaining of pipeline elements and a proper callback method. This pull request cleans up code and makes the mapper implementation closer to the MapReduce internal one.

More fixes for mappers

---

README.md
djangae/db/backends/appengine/base.py
djangae/db/backends/appengine/caching.py
djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/context.py
djangae/db/caching.py
djangae/db/constraints.py
djangae/db/transaction.py
djangae/db/utils.py
djangae/tests/__init__.py
djangae/tests/caching.py
djangae/tests/tests.py

This will blow your minds! Seamless and transparent datastore caching, like NDB only less bonkers and caches on unique field combinations too!

Add memcache and improved context caching layers

---

djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/compiler.py
djangae/db/utils.py
djangae/indexing.py
djangae/tests/tests.py

This makes sure validation happens properly on updates, as well as inserts. It also removes some duplicated code.

Fix integrity errors

---

djangae/contrib/mappers/pipes.py
djangae/contrib/uniquetool/admin.py
djangae/contrib/uniquetool/models.py
djangae/contrib/uniquetool/templates/admin/unique_action_change_form.html
djangae/contrib/uniquetool/tests.py
djangae/db/backends/appengine/commands.py
djangae/fields/related.py
djangae/utils.py

A couple of django admin views for retrofitting the unique constraint markers when adding unique constraints to a model or migrating a model to Djangae.

Uniquetool - A tool for adding in the uniqueness markers to a model that previously didn't have them

---

README.md
djangae/contrib/pagination/README.md
djangae/contrib/pagination/__init__.py
djangae/contrib/pagination/admin.py
djangae/contrib/pagination/decorators.py
djangae/contrib/pagination/models.py
djangae/contrib/pagination/paginator.py
djangae/contrib/pagination/tests.py
djangae/contrib/pagination/views.py
djangae/contrib/sleuth.py

This PR adds a pagination API to contrib. It uses generated fields (specified by a class decorator) to provide efficient pagination on the datastore.

Pagination API

---

djangae/contrib/uniquetool/admin.py
djangae/contrib/uniquetool/models.py
djangae/fields/related.py

Fixes #234 plus small update to the relatedsetfield.

Uniquetool fixes (#234)

---

djangae/contrib/uniquetool/README.md

Add first stab at a readme.

---

djangae/db/constraints.py
djangae/tests/tests.py

Allow unique constraints to work on objects which have a string-based pk of 500 chars

---

djangae/test_runner.py
djangae/tests/tests.py

Minor changes to the test suit to make it run more reliably across different set ups.

Test fixes

---

djangae/utils.py

We had a retry until succesful, generalized it so we can make limited attempts to rerun a function.

Adding a retry function

---

djangae/contrib/mappers/readers.py

This is a mapreduce input reader which (unlike the one in the GoogleAppEngineMapreduce library) works with Windows/Mac/Unix line endings.

Adding `BlobstoreUniversalLineInputReader` to djangae.contrib.mappers.

---

djangae/db/backends/appengine/dnf.py
djangae/tests/tests.py

Implement support for __range queries

---

djangae/contrib/security/commands_utils.py
djangae/contrib/security/management/commands/dumpurls.py

This supersedes #266 (which was created on olasitarska/djangae, so I couldn't push additional commits to it).  That branch is now included in this one.

212 dumpurls

---

djangae/contrib/security/commands_utils.py
djangae/contrib/security/management/commands/dumpurls.py

Added dumpurls command that list all urls and matching routes for the project

---

djangae/db/backends/appengine/caching.py
djangae/db/backends/appengine/context.py
djangae/db/transaction.py
djangae/tests/caching.py

A cleanup on top of Kazade's pull request - getting rid of unsused code.

Fix context caching in transactions #282

---

.gitmodules
.travis.yml
runtests.sh
testapp/django_tests
testapp/install_deps.py

using submodules.
Next step is to make it work with both Django 1.6.11 and 1.7.7

Uses --editable option on pip to install Django with tests instead of

---

djangae/db/backends/appengine/caching.py
djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/context.py
djangae/tests/caching.py

Updated version of #296 with fix

Clear entities from memcache if they were altered inside a transaction

---

djangae/fields/related.py
djangae/tests/tests.py

This makes RelatedSetField even more similar to ManyToManyFields

Allows .add() method to receive multiple items.

---

djangae/db/backends/appengine/commands.py
djangae/tests/caching.py

Test cases attached.
Works fine if you disable caching.

Filters are not applied correctly when filtering with cache enabled

---

README.md
djangae/db/transaction.py
djangae/tests/test_connector.py
djangae/tests/test_transactional.py

Adds transaction.non_atomic and transaction.in_atomic_block

Transaction decorators

---

djangae/fields/counting.py
docs/fields.md

Updating docs accordingly.
Closes #347

Restoring transactional glory to `ShardedCounterField`.

---

djangae/storage.py
djangae/tests/test_storage.py
djangae/urls.py
djangae/views.py
testapp/testapp/settings.py

A hacky replacement for the files api.

Adding an inline post to blobstore replacing the files api calls.

---

djangae/sandbox.py

Comes back to use WSGIRequestInfo but overrides get_request_url method to
do the same as _LocalRequestInfo does.
This should fix #358

Reverts and adapts the bug introduced on 656686c dealing with deferred tasks.

---

djangae/fields/counting.py
djangae/fields/related.py
djangae/tests/test_db_fields.py

This PR adds the ordered RelatedList to djangae, it also refactors RelatedSet into RelatedIter which makes everything a bit nicer.
RelatedList is an iterable field which guarantees order, and allows duplicate PKs.

RelatedList

---

djangae/sandbox.py
djangae/tests/test_utils.py
djangae/utils.py

* save value in SERVER_PORT environment
* check if port is available with port_is_open
* tries next 10 sequentional ports
* test added

Use sequential ports for blobstore #361

---

testapp/testapp/settings.py

Bringing back running all of the Django tests

---

djangae/core/management/__init__.py
djangae/sandbox.py

Fix runserver settings flag

---

README.md
djangae/fields/related.py
djangae/tests/test_db_fields.py
docs/db_backend.md
docs/fields.md

Documenting all the things!  (And tweaking GenericRelationField because I needed to make sure I knew how it worked and that it wasn't broken before I wrote the docs for it.)

Documentation love

---

README.md
docs/contributing.md

Adding a note about code style to the 'Contributing' section of the READMEs.

---

README.md
runtests.sh
testapp/runtests.sh

* Putting all of the functionality into the one in the main directory.
* Removing the unnecessary virtualenv stuff.
* Updating the README accordingly.

Removing one of the 2 `runtests.sh` scripts.

---

djangae/db/backends/appengine/commands.py
djangae/tests/test_connector.py

Prevent update on stale entities

---

djangae/contrib/pagination/decorators.py
djangae/contrib/pagination/tests.py

Allow usage of pk in djangae Paginator

---

djangae/tests/test_connector.py

Add test to show the issue 248 with QueryByKeys is not happening anymore

---

djangae/sandbox.py

Adding a fix to @allow_modules so that it doesn't cause weirdness with os.environ

---

djangae/fields/counting.py
djangae/tests/test_db_fields.py

Making populate() on ShardedCounterField idempotent/more transactional

---

djangae/db/backends/appengine/query.py
djangae/db/utils.py
djangae/fields/iterable.py
djangae/indexing.py
djangae/tests/test_connector.py
testapp/djangaeidx.yaml

Added RegexIndexer and IRegexIndexer

---

djangae/tests/test_query_transform.py
testapp/install_deps.py
testapp/testapp/settings.py

Would be nice to have: only download Django once in install deps.

Fix versions mismatch and fix broken test

---

djangae/contrib/consistency/__init__.py
djangae/contrib/consistency/caches.py
djangae/contrib/consistency/consistency.py
djangae/contrib/consistency/models.py
djangae/contrib/consistency/signals.py
djangae/contrib/consistency/tests.py
docs/consistency.md
docs/index.md
mkdocs.yml
testapp/testapp/settings.py

Ported from https://github.com/adamalton/djangae-consistency.

Adding djangae.contrib.consistency.

---

djangae/contrib/gauth/tests.py
djangae/contrib/gauth/urls.py
djangae/contrib/gauth/utils.py
djangae/contrib/gauth/views.py
docs/gauth.md
testapp/testapp/urls.py

Adding 'switch accounts' functionality to gauth.

---

docs/fields.md
docs/uniquetool.md

I am not sure what is the best place to mention about `UniquenessMixin`. The info about `unique` appears in `fields.md`, but the `uniquetool.md` seems to be focused on the uniqueness. If we provide one single example (without emphasizing the mixin) from the `fields.md`, it might be overlooked.
Sorry for the American English.

Docs on UniquenessMixin

---

.travis.yml
djangae/storage.py

CloudStorage backend

---

djangae/blobstore_service.py

Disabling logging for blobstore requests. 

---

djangae/contrib/sleuth.py
djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/query.py
djangae/db/utils.py
djangae/tests/test_connector.py

Gives everyone a huge performance boost!

Query by keys refactor

---

docs/contributing.md
docs/installation.md
testapp/install_deps.py
testapp/requirements.txt

- Update AppEngine SDK to currently newest
- Update django versions in docs (shifting everything by 1)
- Add simplejson to requirements.txt (this was missing when I tried to run the tests the first time)

tests: update SDK to 1.9.26, docs: update versions

---

djangae/core/management/__init__.py
djangae/management/commands/runserver.py

This PR fixes switching django's settings module doesn't work now.
On local environment, djangae's runserver has capability of switching django's settings module by --settings. But its not passed into appropriate module's environment variable, even default django wsgi instance.
You can switch settings as it is. Addition, when you pass --${mod}-settings to the runserver command, its passed into the module's DJANGO_SETTINGS_MODULE environment variable.

fix django settings propagation which is passed as a command line argument

---

docs/gauth.md

We were referencing the wrong classes for the abstract user models.
Thanks Micahel Wu.

Fix mistakes in gauth docs.

---

djangae/db/backends/appengine/base.py
djangae/tests/test_connector.py

Fix DurationField stored value bug

---

djangae/contrib/gauth/common/models.py

Reverts potatolondon/djangae#522

Revert "Allow User ID to be blank"

---

djangae/db/backends/appengine/base.py
djangae/db/backends/appengine/dbapi.py

Sorry, no test cases, cuz I could not get the already-existing tests to run without error.

Added binary field

---

djangae/storage.py
docs/index.md
docs/storage.md

Basic storage docs, will add more as needed
#419

Storage docs

---

djangae/db/backends/appengine/query.py
djangae/tests/test_connector.py

Special index queries on PK fields

---

djangae/management/commands/runserver.py
djangae/sandbox.py

Patches devappserver2 to support skip_files. This will *not* work with directories unless further patching is done as it only matches on filenames.

add skip_files patch

---

djangae/management/commands/runserver.py

Additional settings for additional skip_files

add additional djange-skip-files

---

djangae/contrib/mappers/pipes.py
docs/mappers.md

Allow use of queue_name to run map-reduce tasks on a specific queue

---

djangae/fields/json.py
djangae/tests/test_db_fields.py

Fix serialisation of float values in JSONFields.

---

djangae/fields/counting.py

Without this, ShardedCounterField uses the deconstruct() method from RelatedSetField which is incorrect.
I've also added a check to prevent setting "default" which can't easily be supported (logically it should be a number, but that would require running increment earlier than possible).

Add a valid deconstruct method to ShardedCounterField

---

djangae/db/backends/appengine/base.py
djangae/db/backends/appengine/caching.py
djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/context.py
djangae/db/caching.py
djangae/db/transaction.py
djangae/tests/test_caching.py

Closes #578
@adamalton Could you review this and try to think of a case where it could cause issues - I think we're fine because the RPC will still evaluate the same it just lets the current thread continue, and we have the future thing to ensure set then get works.

Improve memcache performance

---

djangae/sandbox.py

Don't die in allow_mode_write if the tempfile module is unavailable

---

djangae/contrib/gauth/common/models.py
djangae/contrib/gauth/middleware.py
djangae/contrib/gauth/tests.py
docs/gauth.md

Make Gauth always add users with their emails lowercased.

---

CHANGELOG.md
djangae/db/consistency.py
djangae/tests/test_utils.py
docs/db_backend.md

Better naming, more features, such wow.

Adds ensure_instances_consistent, and deprecates ensure_instance_included

---

docs/consistency.md
docs/fields.md
docs/index.md

* Updating statement about supported Django versions.
* Adding documentation for computed fields.
* Clarifying that the `CONSISTENCY_CONFIG` belongs in settings.py.

Documentation updates/tweaks.

---

djangae/contrib/gauth/common/backends.py
djangae/contrib/gauth/tests.py

This is (probably) a fix for #624.
But note that in #624 the `IntegrityError` being raised is for the `email` field, whereas if you undo this fix and run the new test without it then the `IntegrityError` you get is for the `username` field. But also note that the traceback in #624 shows a custom user model.
Also note that this fix catches `django.db.utils.IntegrityError`, whereas if you look at the code where the exception is raised then you would think that it should be catching `djangae.db.backends.appengine.dbapi.IntegrityError`.  I have no idea how that exception morphs itself from one to the other!  Maybe #625 will fix that?!

Making auth backend catch race condition when creating a new user.

---

djangae/contrib/mappers/pipes.py

This PR changes to the default db to be the one returned by the applications router.

Ensure MapReduceTask uses the db returned by the application router(s)

---

djangae/storage.py

For example, support `<input type="file" name="files[]">`

BlobstoreFileUploadHandler supports brackets in file input name

---

CHANGELOG.md
TODO.md
djangae/core/management/__init__.py
djangae/db/backends/appengine/indexing.py
djangae/db/backends/appengine/query.py
djangae/environment.py
djangae/management/commands/runserver.py
djangae/sandbox.py
djangae/test_runner.py
djangae/utils.py
djangae/views.py
djangae/wsgi.py
docs/db_backend.md
docs/environment.md

This PR adds djangae/environment.py and relocates several functions from djangae/utils.py.
It also adds some extra functions for detecting information about task queues.

Improve environment utility methods

---

CHANGELOG.md
README.md
docs/contributing.md

This pull requests add some getting started instructions on how to contribute to Djangae.

Improving the contributing documentation

---

djangae/sandbox.py

Fixes bug in master.
- Fixes a bug introduced in a previous PR which caused system-wide paths to have priority over SDK ones
PR checklist:
The previous change broke things by prioritising system-wide python paths over
App Engine ones. This fixes that by only prioritising paths which are under the project
root and making sure all other paths come after the SDK.

Make sure the ordering of paths on sys.path is correct

---

CHANGELOG.md
djangae/contrib/gauth/middleware.py
docs/gauth.md

- refactoring of `AuthenticationMiddleware` - user data synced inside a method, that allows to 
easily inherit from the middleware and override the method.
Related ticket: #691
PR checklist:

Customize gauth middleware

---

CHANGELOG.md
docs/db_backend.md
docs/fields.md
docs/gauth.md
docs/installation.md
docs/sandbox.md

Various improvements to the documentation.
- See commit titles, or CHANGELOG entry.
PR checklist:

Semi regular documentation love

---

CHANGELOG.md
djangae/__init__.py

- add version number to __init__
PR checklist:
- [N/A] Added tests for my change

add version string to __init__

---

djangae/contrib/gauth/common/models.py

Add missing `max_length` kwarg to `GaeAbstractBaseUser.email_lower`.

---

CHANGELOG.md
djangae/db/backends/appengine/indexing.py
djangae/tests/test_connector.py
docs/db_backend.md

- Allows apps to ship their own djangaeidx.yaml
PR checklist:

App specific djangaeidx

---

setup.py

Fixes #732 
fixed typo in setup.py

fixed typo in setup.py

---

djangae/db/backends/appengine/base.py

Again, a tiny change to make Wagtail run ;)

Adding few passing methods to let migrations pass

---

CHANGELOG.md
djangae/__init__.py
djangae/apps.py
djangae/sandbox.py
djangae/urls.py
djangae/views.py
docs/sessions.md
testapp/testapp/wsgi.py

Fixes #549
-  clearsessions
-  sandbox and patch fixes
PR checklist:

Clearsessions

---

docs/gauth.md

- Adds docs about possible `get_or_create` problems when using pre-created users.
PR checklist:

Email lower docs

---

CHANGELOG.md
djangae/management/commands/runserver.py

Make the --nothreading argument to runserver work

---

djangae/contrib/pagination/__init__.py
djangae/contrib/pagination/paginator.py
djangae/contrib/pagination/tests.py
djangae/contrib/pagination/views.py

It's all said in the title! No rocket science here!

Better formatting (PEP8)

---

CHANGELOG.md
djangae/contrib/gauth/middleware.py
djangae/contrib/gauth/tests.py

Fixes #781 .
- Fixed auth middleware to update user email address if it gets changed
PR checklist:

Update user email address in gauth middleware if it gets changed

---

CHANGELOG.md
djangae/fields/iterable.py
djangae/fields/related.py
djangae/tests/test_db_fields.py

Fixes #794 
- Add additional related filtering tests (closes #795)
- Fix the test by correcting the incorrect overlap lookup
PR checklist:

Grzes 794 iterable fixes

---

CHANGELOG.md
djangae/fields/related.py
djangae/tests/test_db_fields.py

Fixes #774 
- Implements prefetch_related behaviour on RelatedListField and RelatedSetField
PR checklist:

Allow prefetching relatedsetfield

---

CHANGELOG.md
djangae/apps.py
djangae/checks.py

Moving djangae-scaffold system checks into djangae.

---

CHANGELOG.md
djangae/forms/fields.py
djangae/tests/test_db_fields.py
djangae/tests/test_form_fields.py
docs/fields.md

Fixes #816 
- Improves the validation logic in JSONFormField
PR checklist:

Fix up issues with JSONFormField

---

CHANGELOG.md
djangae/fields/json.py
djangae/tests/test_db_fields.py

Fixes #769 
- Fixes a bug that would prevent loading instances with invalid JSON data
PR checklist:

Fix json field saving loading

---

CHANGELOG.md
djangae/contrib/gauth/common/models.py
djangae/contrib/gauth/datastore.py
djangae/contrib/gauth/sql.py

Add backwards compatibility for paths that have changed in djangae.contrib.gauth.

---

djangae/contrib/gauth/tests.py
djangae/contrib/gauth/views.py

Currently if a user clicks on switch account but then decides to use the same account, they'll get logged out. If they then try to login again, they'll get redirected to `switch_accounts` which will log them out again. The user will then get stuck in a loop with no way of getting back into your app from the same tab - they'll have to open a new tab, sign into their Google account and then open your app.
The way I've partially solved this is to add a session variable for storing if the user already been redirected to `create_logout_url`. It'll work like this:
User is signed in to a single Google account
- User goes to `switch_accounts` view.
- `switch_accounts` redirects to `create_login_url`.
- User is signed in to one Google account, so returns to `switch_accounts`.
- `switch_account` …

Detect when user is switching to the same account

---

CHANGELOG.md
djangae/fields/related.py
djangae/tests/test_db_fields.py

Fixes #829
- Adds a test to ensure prefetching works correctly
- Cleans up some of the related iterator code 
PR checklist:

Write a test for #829

---

.travis.yml

Add djangae slack instance to travis notifications

---

CHANGELOG.md
djangae/sandbox.py
testapp/install_deps.py

Fixes #873 
- Workaround for changes in the latest SDK relating to the devappserver
PR checklist:

Fix the sandbox to work on the 1.9.51 SDK

---

djangae/fields/related.py
djangae/forms/fields.py

Makes a couple of improvements to the changes that were made in #917.
No changelog entry, as it's just changing the same things that have already been changed.

Related list field form tweaks

---

djangae/contrib/sleuth.py
djangae/tests/test_urls.py
testapp/requirements.txt

Fixes #926
Closes: #927 
- Fixes a bug where Djangae would import mapreduce unintentionally
PR checklist:

Davidwtbuxton djangae urls and mapreduce

---

CHANGELOG.md
djangae/sandbox.py
testapp/install_deps.py

Fixes #925 
- Fixes the sandbox setup in 1.9.54 (thanks @TysonRV!)
PR checklist:

Fix 1.9.54 sdk

---

CHANGELOG.md
djangae/db/backends/appengine/meta_queries.py
djangae/tests/test_connector.py

- Turns out we forgot to implement offsets and limits - I'm amazed this didn't show up in tests!
PR checklist:

Fix multi-query offsets and limits

---

CHANGELOG.md

- Move JSON changelog notes to the correct version
PR checklist:
- [N/A] Added tests for my change

Move JSON changelog notes to correct version

---

CHANGELOG.md
djangae/core/paginator.py
djangae/tests/test_paginator.py

Fixes #839 
- Page queries are now executed when .page() is called
- Fixed bugs where the original queryset was manipulated when page() was called
- Wrote some tests
PR checklist:
- [] Updated relevant documentation

Core paginator fixes

---

djangae/contrib/gauth_sql/backends.py

- Fix outdated import in gauth_sql app  
This is causing an error making me unable to use gauth_sql

Fix bad import on gauth_sql

---

CHANGELOG.md
djangae/sandbox.py
djangae/tests/test_connector.py
testapp/manage.py

- Set appropriate environment variables in the test sandbox
- Enable the blobstore service in the test sandbox
- Use the test sandbox for the testapp (effectively testing the test sandbox!)
PR checklist:

Test sandbox environment fixes

---

CHANGELOG.md
djangae/db/backends/appengine/indexing.py
djangae/sandbox.py

- Fix a circular import that could sometimes occur
- Initialize the app_identity stub as part of the test sandbox
PR checklist:

Two minor fixes

---

docs/index.md
docs/release_notes/0_9_10.md
docs/release_notes/index.md
mkdocs.yml

Improves the way that release notes are listed in the Readthedocs documentation.

Improve release notes in readthedocs

---

CHANGELOG.md
djangae/fields/iterable.py
djangae/tests/test_db_fields.py

Make SetField and ListField pickleable when they have a default value set

---

.github/ISSUE_TEMPLATE.md

This will hopefully help avoid so many questoins being submitted as issues.
What do you think @Kazade?

Add github issue template.

---

CHANGELOG.md
djangae/db/backends/appengine/commands.py
djangae/db/backends/appengine/formatting.py
djangae/db/backends/appengine/query.py
djangae/tests/test_sql_formatting.py

Fixes #942 
- Greatly improves the approximate SQL representation in connection.queries
PR checklist:

Improve sql representation

---

CHANGELOG.md
MANIFEST.in
djangae/tests/test_db_fields.py

Fixes #1009 
- Add missing `djangae/fields/allkeys-5.2.0.zip` file to `MANIFEST.in`.
PR checklist:

Fix ComputedCollationFields

---

README.md

Remove failing issuestats images

---

CHANGELOG.md
djangae/fields/__init__.py
djangae/fields/files.py
djangae/tests/test_db_fields.py
docs/fields.md

These provide the additional `url_field` argument to allow caching of the URL in another field on the model.
PR checklist:

Add custom FileField and ImageField

---

CHANGELOG.md
djangae/db/backends/appengine/meta_queries.py
djangae/fields/related.py
djangae/tests/test_db_fields.py

Fixes #997 
- RelatedListField querying no longer fetches data unnecessarily
- values_list now works properly on RelatedListField querysets
PR checklist:

Fix a number of issues with RelatedListField querying

---

docs/storage.md

- remove duplicated word in howto document

remove duplicated word in docs

---

CHANGELOG.md
djangae/fields/language.py

Allows computed collation on None values.

Change the ComputedCollation field logic to allow null values

---

CHANGELOG.md
djangae/deferred.py
djangae/tests/test_deferred.py
docs/deferred.md

Fixes #1033 
- Add a defer function in a new `djangae.deferred` module
PR checklist:

Implement djangae.deferred.defer. Fixes #1033

---

CHANGELOG.md
djangae/fields/language.py
djangae/tests/test_computed_collation_field.py

Fixes #1048 
- Fixes incorrect sort key generation
- Warns and truncates sort keys which are too long
PR checklist:

Fix computed collation field

---

CHANGELOG.md
djangae/tests/test_utils.py
djangae/utils.py
docs/utils.md

Change `_retries` param to `_attempts` in `retry`

---

djangae/db/migrations/mapper_library.py

- This bug-fixes the previous bug fix (#1059) which the string difference calculation was wrong.
PR checklist:

Fix string value calculation (thanks David Buxton!)

---

CHANGELOG.md
setup.py

Fixes #1065.
Will need a release to PyPI before it takes effect, obvs.

Fixed Djangae's project description on pypi.org.

---

CHANGELOG.md
djangae/db/backends/appengine/formatting.py
djangae/tests/test_db_fields.py
djangae/tests/test_sql_formatting.py

Fixes #1072 
- Replace binary values in sql value generation with `<binary>` identifier.
PR checklist:
- [N/A] Updated relevant documentation

BinaryField fix and unit tests

---

CHANGELOG.md
djangae/db/backends/appengine/commands.py
djangae/tests/test_connector.py

Fixes #1026 
- Works around an App Engine bug where projected values would return `str` instead of `unicode`
PR checklist:

Fix values list return type

---

CHANGELOG.md
djangae/db/backends/appengine/meta_queries.py
djangae/tests/test_connector.py

- Fix a bug where some results may not be returned if you are offsetting a multiquery
PR checklist:

Fix a bug in AsyncMultiQuery

---

djangae/db/backends/appengine/meta_queries.py
djangae/tests/test_connector.py

- This fixes a bug introduced in #1087 (so the changelog hasn't been updated)
PR checklist:

Fix asyncmultiquery limiting

---

CHANGELOG.md
djangae/db/utils.py
djangae/tests/test_db_fields.py

Fixes #1083 
- Need to do proper db prep of field before saving when using default value
PR checklist:
- [no ] Updated relevant documentation

Need to do proper db prep of field before saving when using default value

---

CHANGELOG.md
djangae/test.py
djangae/tests/test_test.py
testapp/queue.yaml

Fixes #1081 
- option to ignore pull tasks when retrieving in test
- never process pull tasks
PR checklist:
- [N/A ] Updated relevant documentation

ignore pull tasks in test

---

CHANGELOG.md
djangae/fields/json.py
djangae/tests/test_jsonfield.py

- Fixes a bug when serializing and deserializing unsaved instances with JSONFields
PR checklist:

Fix JSONField serialization/deserialization

---

CHANGELOG.md
djangae/checks.py
djangae/tests/test_checks.py

Fixes #1100.
- add gcloud version check in `checks.py`
- tests
PR checklist:

check google cloud sdk version on local server start

---

CHANGELOG.md
djangae/admin.py
djangae/db/migrations/mapper_library.py
djangae/deferred.py
djangae/models.py
djangae/processing.py
djangae/test.py
djangae/tests/test_defer_iteration.py
docs/deferred.md

- Adds a nice method for iterating large querysets in deferred tasks
PR checklist:

Add `deferred.defer_iteration_with_finalize`

---

djangae/contrib/locking/lock.py
djangae/contrib/locking/models.py
djangae/contrib/locking/tests.py

- Fixes previous merge
PR checklist:

Allow passing through max_wait_ms

---

djangae/sandbox.py
djangae/tasks/__init__.py
djangae/tasks/deferred.py
tox.ini

- Use the correct path format when creating tasks queues
PR checklist:

Fix the path when creating queues

---

djangae/utils.py

- Move some imports inline to fix a potential circular import
PR checklist:

Move imports inline in utils.py to avoid a circular import

---

djangae/contrib/locking/views.py

- Move an import inline to prevent potential circular import
PR checklist:

Fix potential circular import error

---

djangae/tasks/deferred.py

- Fix potential circular error
PR checklist:

Make deferred url lazy

---

djangae/tasks/test.py

Bring back `assertNumTasksEquals`

---

djangae/tasks/deferred.py

- A couple of small fixes to deferred.py
PR checklist:

Deferred task fixes

---

djangae/tasks/deferred.py

Force-clear ordering while generating task shards

---

djangae/tasks/test.py

Ensure all queues are re-checked for subsequent deferred

---

CHANGELOG.md
djangae/contrib/security/middleware.py
djangae/contrib/security/tests.py

- update functions for Python 3.7 compatibility

Update security middleware for Python 3.7 compatibility

---

CHANGELOG.md
djangae/contrib/backup/urls.py
djangae/contrib/locking/urls.py

- update url patterns to use the Django 2 `path` function

Update urls to use path

---

CHANGELOG.md
djangae/contrib/security/commands_utils.py

- fix the `djangae.contrib.security.commands_utils.extract_views_from_urlpatterns` function for Python 3 and Django 2.2

Fix extract_views_from_urlpatterns function

---

CHANGELOG.md
djangae/storage.py
djangae/tests/test_storage.py

- fix an issue with `CloudStorage` where it was using the `_bucket` instance variable instead of the `bucket` property

Fix CloudStorage methods

---

CHANGELOG.md
djangae/utils.py

- fix error classes not inheriting from `Exception`

Fix error classes

---

CHANGELOG.md
setup.py

- add `google-cloud-tasks` as a requirement
PR checklist:

Add google-cloud-tasks as a requirement

---

djangae/contrib/googleauth/models.py
docs/googleauth.md

- Adds AbstractGoogleUser 
PR checklist:

Fix user model abstraction

---

djangae/credentials/__init__.py
djangae/credentials/tests/test_init.py

Fixes #1258 
- Fixed Credentials default  check for production environment
- Added tests to make sure the right instance is returned based on environment
PR checklist:

Fix Credentials default and add tests #1258

---

setup.py

Upgrade django-gcloud-connectors dependency
PR checklist:

Bump gcloudc version

---

djangae/contrib/googleauth/backends/oauth2.py

Fixes #1266
- Make sure the registered user model is used in oauth auth
PR checklist:

Get registered user model #1266

---

djangae/contrib/googleauth/tests/test_oauth.py
djangae/contrib/googleauth/tests/test_views.py
djangae/contrib/googleauth/views.py
djangae/environment.py
docs/googleauth.md

Fixes #1268 
- Add configuration to specify OAUTH2 redirect host
- Store incoming app version in oauth state
- Redirect to the right appengine from oauth2callback
PR checklist:

1268 gae versions

---

djangae/tasks/deferred.py

- Add missing `headers` key when deferring larger tasks.

Add missing headers payload

---

djangae/contrib/search/fields.py
djangae/contrib/search/index.py
djangae/contrib/search/query.py
djangae/contrib/search/tests/test_indexing.py
djangae/contrib/search/tests/test_query.py
djangae/contrib/search/tokens.py

- Makes search behaviour match documentation (e.g. AND rather than OR behaviour by default) 
- Add match_all flag to make this configurable
PR checklist:

Search match all

---

djangae/sandbox.py
setup.py

Fixes #1285 
- Kill all emulator children
PR checklist:

Kill emulator children #1285

---

djangae/contrib/search/query.py
djangae/contrib/search/tests/test_query.py

- Fix an issue with false-positives when using startswith search matching
PR checklist:

Fix search matching issue

---

djangae/contrib/search/index.py
djangae/contrib/search/model_document.py

Default index name for ModelDocument
PR checklist:

1295 model document index

---

djangae/contrib/search/fields.py
djangae/contrib/search/tests/test_field.py

- Guard for string out of range
- Still indexing tokens that contains only +s
- Add a few tests for clean_token
PR checklist:

Fix string index out of range #1297

---

djangae/contrib/search/query.py
docs/contrib_search.md

- Limit the number of results per-token to prevent slow search queries
PR checklist:

Avoid excessively large token resultsets

---

djangae/sandbox.py

- small update to `logging.info` call to include both parameters
PR checklist:

Update logging to include PID

---

djangae/contrib/search/tests/test_searchable.py

Add an additional stopword test

---

djangae/contrib/search/model_document.py
djangae/contrib/search/query.py
djangae/contrib/search/tests/test_searchable.py

- Fix issues with the SearchQuerysetManager
PR checklist:

Fix issues with the search queryset and manager

---

djangae/contrib/search/index.py
djangae/contrib/search/model_document.py

- Fix an assertion if eventual consistency had resulted in a document being indexed multiple times
- Wrap token indexing in independent transactions to alleviate problems indexing
PR checklist:

Search fixes

---

djangae/contrib/search/tests/test_indexing.py
djangae/contrib/search/tokens.py

Fixes #1322
- fixed tokenisation issue
PR checklist:

1322 token issue
